import { ComponentInterface, EventEmitter } from '../../../stencil-public-runtime';
import { HTMLStencilElement } from '../../../stencil-public-runtime';
export declare class PichinchaOtp implements ComponentInterface {
  boxs: number;
  timer: number;
  titleOtp: string;
  disabled: boolean;
  errorAlertText: string;
  nextButtonLabel: string;
  backButtonLabel: string;
  contactDescription: string;
  contactHelpLabel: string;
  textShowCode: string;
  textHideCode: string;
  textResendCode: string;
  textResendingCode: string;
  textCodeSent: string;
  textShowHideCode: string;
  timerText: string;
  description: string;
  typePassword: boolean;
  stateButton: 'normal' | 'loading';
  status: 'normal' | 'error';
  errorCode: '1' | '2' | '';
  stateResend: 'loading' | 'success' | 'error' | '';
  hideBackButton: boolean;
  fullWidth: boolean;
  showInfo: boolean;
  timeExpired: EventEmitter;
  clickGoBack: EventEmitter;
  clickContinue: EventEmitter;
  clickResend: EventEmitter;
  inputsOtpState: any;
  showingCode: boolean;
  inputType: string;
  otpValue: string;
  currentStatus: 'normal' | 'error';
  clearOtp: boolean;
  showAlert: boolean;
  time: number;
  interval: any;
  updateCurrentStatus(): void;
  setShowAlert(): void;
  watchTimerHandler(): void;
  private hasBodySlot;
  private hasInfoSlot;
  hostElement: HTMLStencilElement;
  componentWillLoad(): void;
  componentDidUpdate(): void;
  disconnectedCallback(): void;
  handleClick(e: any, emitter: EventEmitter): void;
  private handleClickDown;
  private handleClickUp;
  private getTimeOtp;
  private calcTimeOtp;
  private createToken;
  private createTime;
  private setStatus;
  private get infoContent();
  private get otpContainerClass();
  private get btnsContainerClass();
  private get otpInputContainerClass();
  render(): any;
}
