import { EventEmitter, ComponentInterface } from '../../../stencil-public-runtime';
import { STATE, SIZE, SelectItems } from './multiselect.type';
export declare class Multiselect implements ComponentInterface {
  private valueSelectedItems;
  idElement: string;
  state: STATE;
  size: SIZE;
  placeholder: string;
  items: SelectItems[];
  label: string;
  normalHelper: string;
  errorHelper: string;
  countSelectedOptions: number;
  fullWidth: boolean;
  tooltip: string;
  open: boolean;
  isFocus: boolean;
  clickedItem: EventEmitter;
  el: HTMLElement;
  componentDidLoad(): void;
  componentWillLoad(): void;
  closeListeners(element: HTMLElement): void;
  disconnectedCallback(): void;
  updateVisualItems(): void;
  handleClick: (selectedItem: SelectItems) => void;
  private onFocusIn;
  onFocusOut: () => void;
  selectedByDefault(): void;
  private updateSelected;
  private controlDropDown;
  private getMainClass;
  getInputContainerClass(): string;
  private getInputChildClass;
  private getInputLabelClass;
  getItemLabelClass(): string;
  getItemCounterLabelClass(): string;
  private getListClass;
  private getItemListClass;
  render(): any;
}
