import { EventEmitter } from '../../../stencil-public-runtime';
export declare class PichinchaCallmeback {
  contactName: string;
  contactNumber: string;
  hidden: boolean;
  showText: boolean;
  showUpdate: boolean;
  loadingButton: boolean;
  step: 'confirm' | 'success' | 'update' | 'error';
  buttonText: string;
  confirmTitle: string;
  confirmDescription: string;
  confirmPrimaryButton: string;
  confirmSecondaryButton: string;
  updateTitle: string;
  updateDescription: string;
  updatePrimaryButton: string;
  updateSecondaryButton: string;
  successTitle: string;
  successDescription: string;
  successPrimaryButton: string;
  errorTitle: string;
  errorDescription: string;
  errorPrimaryButton: string;
  disabledButtonUpdate: boolean;
  modal: boolean;
  isMobile: boolean;
  bottom: string;
  clickCallMeBack: EventEmitter;
  clickUpdateButton: EventEmitter;
  clickSuccessButton: EventEmitter;
  clickErrorButton: EventEmitter;
  clickCloseModal: EventEmitter;
  clickFloatButton: EventEmitter;
  customEvent: EventEmitter;
  lastScrollTop: number;
  changeAnimation(): void;
  handleScreen(): void;
  handleClose(): void;
  selectEvent(): EventEmitter<any>;
  handleClick(e: any, emmiter: EventEmitter): void;
  handleClickSecondaryButton(): void;
  setVariablesInText(text: any): any;
  render(): any;
}
