/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
import { Actions, Header, Row } from "./components/organisms/table/intefaces";
import { AlignContent, AlignItems, Colors, Direction, Justify, VariantText, VariantWebviewsText, Wrap } from "./global/interfaces";
import { Size } from "./global/utils";
import { IconTypes } from "./components/atoms/icon/icon.types";
import { COLORS, ListItems, VARIANT, WEIGHTCOLOR } from "./components/atoms/list/list.type";
import { SelectItems, SIZE, STATE } from "./components/atoms/multiselect/multiselect.type";
import { SelectItem, SIZE as SIZE1, STATE as STATE1 } from "./components/atoms/select/select.type";
import { Term } from "./components/organisms/selector-box/term";
import { TabActivateEvent } from "./components/atoms/tab/tab";
import { AllColorType } from "./global/constants/colors-constants";
export namespace Components {
    interface ActionTable {
        "actions": Actions[];
        "indexRow": number;
        "lastRow": number;
        "row": Row;
        "status": string;
    }
    interface BadgeTable {
        "row": Row;
        "status": string;
    }
    interface MovilEmail {
        "value": string;
    }
    interface PichinchaAccordion {
        /**
          * close the accordion item
         */
        "closeItem": () => Promise<void>;
        "description": string;
        /**
          * index of accordion item from top to bottom
         */
        "index": number;
        /**
          * The mutation observer config to listen for content changes in the accordion item
         */
        "mutationObserverConfig": { childList: boolean; subtree: boolean; };
        "name": string;
        /**
          * accordion item is open or opening (css transition)
         */
        "openAccordion": boolean;
        /**
          * open the accordion item
         */
        "openItem": () => Promise<void>;
    }
    interface PichinchaAccountSelectWebview {
        /**
          * Account name. E.g. "Cta. Ahorros". Position top-left
         */
        "accountName": string;
        /**
          * Account number. Position bottom-left
         */
        "accountNumber": string;
        /**
          * Account number. Position bottom-right
         */
        "amount": string;
        /**
          * Amount Label. E.g. "Saldo disponible". Position top-right
         */
        "amountLabel": string;
        /**
          * Screen reader label
         */
        "ariaLabel": string;
        /**
          * Id of the element
         */
        "idElement": string;
    }
    interface PichinchaAlertMessage {
        /**
          * Text for the Accept Button
         */
        "acceptButtonText"?: string;
        /**
          * Adjust in container
         */
        "adjustIn": boolean;
        /**
          * Alert message title string to show
         */
        "alertTitle"?: string;
        /**
          * Show icon to close
         */
        "allowClose"?: boolean;
        /**
          * Text for the Cancel Button
         */
        "cancelButtonText"?: string;
        /**
          * Close the alert-message after x milliseconds
         */
        "closeTime"?: number;
        /**
          * Alert will show a valid Icon
         */
        "hasIcon": boolean;
        /**
          * Icon to show in message
         */
        "icon"?: string;
        /**
          * Element id
         */
        "idElement"?: string;
        /**
          * Closed by default, if it's true shows the component
         */
        "open": boolean;
        /**
          * Can be: 'success', 'error', 'warning' or 'info' By default 'info' if not specified
         */
        "status": 'success' | 'error' | 'warning' | 'info';
        /**
          * Position absolute
         */
        "top"?: number;
    }
    interface PichinchaAvatar {
        "name": string;
        "size": 'xs' | 'sm' | 'md' | 'lg' | 'xl' | 'xxl';
        "src": string;
        "type": | 'image'
    | 'icon'
    | 'name';
    }
    interface PichinchaBrand {
        "color": "primary" | "white" | "black" | "yellow" | "blue";
        "height": number;
        "type": "logo" | "emblem";
        "width": number;
    }
    interface PichinchaButton {
        "ariaLabel": any;
        /**
          * The color
         */
        "color": | 'primary'
    | 'secondary'
    | 'complementary'
    | 'tertiary'
    | 'destructive';
        "disabled": boolean;
        "href": string;
        "iconName"?: string;
        "iconNameRight"?: string;
        "iconType"?: | '--outlined'
    | '--round'
    | '--sharp'
    | '--two-tone';
        "idelement": string;
        "loading": boolean;
        "onlyIcon": boolean;
        "size": 'medium' | 'small' | 'large' | 'extra-large';
        "tabIndexInner": number;
        "type": string;
        "value": string;
    }
    interface PichinchaCallmeback {
        "buttonText": string;
        "confirmDescription": string;
        "confirmPrimaryButton": string;
        "confirmSecondaryButton": string;
        "confirmTitle": string;
        "contactName": string;
        "contactNumber": string;
        "disabledButtonUpdate": boolean;
        "errorDescription": string;
        "errorPrimaryButton": string;
        "errorTitle": string;
        "hidden": boolean;
        "loadingButton": boolean;
        "showText": boolean;
        "showUpdate": boolean;
        "step": 'confirm' | 'success' | 'update' | 'error';
        "successDescription": string;
        "successPrimaryButton": string;
        "successTitle": string;
        "updateDescription": string;
        "updatePrimaryButton": string;
        "updateSecondaryButton": string;
        "updateTitle": string;
    }
    interface PichinchaCarousel {
        "timeAutoPlay"?: number;
    }
    interface PichinchaCarouselItem {
        "isActive": boolean;
    }
    interface PichinchaCheckBox {
        "checked": boolean;
        "disabled": boolean;
        "error": boolean;
        /**
          * The color
         */
        "idElement": string;
        "nameElement": string;
        "offLabelClick": boolean;
        "typeCheck": string;
        "value": string;
    }
    interface PichinchaErrorReloadWebview {
        "ariaHidden": string | undefined;
        /**
          * Description in the component
         */
        "description": string;
        /**
          * Id of the element
         */
        "idElement": string;
        /**
          * Text link in the component
         */
        "reloadText": string;
    }
    interface PichinchaFeedback {
        "img": string;
        "showButton": boolean;
        "title": string;
    }
    interface PichinchaFeedbackWebview {
        /**
          * Screen reader label
         */
        "ariaLabel": string;
        /**
          * Description of the component
         */
        "description": string;
        /**
          * Id of the element
         */
        "idElement": string;
        /**
          * State of the feedback. It changes the icon that is displayed
         */
        "state": 'error' | 'warning' | 'success' | 'info';
        /**
          * Title of the component
         */
        "subtitle": string;
        /**
          * Type of feedback. Can be Title or Subtitle
         */
        "variant": 'subtitle' | 'title';
    }
    interface PichinchaGrid {
        "align_content": AlignContent;
        "align_items": AlignItems;
        "container": boolean;
        "direction": Direction;
        "item": boolean;
        "justify": Justify;
        "lg": Size;
        "md": Size;
        "sm": Size;
        "spacing": Size;
        "wrap": Wrap;
        "xl": Size;
        "xs": Size;
    }
    interface PichinchaGridV2 {
        "align_content": AlignContent;
        "align_items": AlignItems;
        "container": boolean;
        "direction": Direction;
        "isDefaultMargin": boolean;
        "item": boolean;
        "justify": Justify;
        "lg": Size;
        "md": Size;
        "sm": Size;
        "wrap": Wrap;
        "xl": Size;
        "xs": Size;
    }
    interface PichinchaHeaderWebview {
        /**
          * Hide from screen reader the header
         */
        "accesibilityHidden": string;
        /**
          * Title read by screen reader
         */
        "ariaTitle": string | undefined;
        "showBreadcrumb": boolean;
        /**
          * Title in the header
         */
        "textTitle": string;
    }
    interface PichinchaIcon {
        /**
          * The color of the icon
         */
        "color"?: Colors;
        /**
          * Inline styles for the icons container
         */
        "inline_styles"?: { [key: string]: string };
        /**
          * The size of the icon
         */
        "size": string;
        /**
          * The weight of the icon
         */
        "type"?: IconTypes;
        /**
          * The weight of the icon
         */
        "weight_color"?: | '100'
    | '200'
    | '300'
    | '400'
    | '500'
    | '600'
    | '700'
    | '800'
    | '900';
    }
    interface PichinchaInput {
        "autoComplete": boolean;
        "autofocus": boolean;
        "class": string;
        "controlEvent": boolean;
        "errorHelper": string;
        "filterRegex": string;
        "floatingLabel": boolean;
        "fullWidth": boolean;
        "hideNumberHandles": boolean;
        "hidePasswordText": string;
        "idElement": string;
        "inlineStyles": { [key: string]: string };
        "inputmode": string;
        "label": string;
        "maxLength": number;
        "nameElement": string;
        "normalHelper": string;
        "pattern": string;
        "placeholder": string;
        "showIconStatus": boolean;
        "showMaxLength": boolean;
        "showPasswordText": string;
        "showPasswordToggle": boolean;
        "showTooltipOnChange": boolean;
        "size": 'extra-small' | 'small' | 'medium' | 'large';
        "state": 'normal' | 'disabled' | 'success' | 'error';
        "tabIndexElement": number;
        "tooltip": string;
        "tooltipBody": any;
        "type": string;
        "value": string;
    }
    interface PichinchaInputWebview {
        /**
          * Screen reader label
         */
        "ariaLabel": any;
        /**
          * Screen reader role description
         */
        "ariaRoleDescription": any;
        "autoComplete": boolean;
        "autofocus": boolean;
        /**
          * Lost focus to hide soft keyboard in mobile browsers
         */
        "blurOnEnter": boolean;
        "class": string;
        "controlEvent": boolean;
        "errorHelper": string;
        "filterRegex": string;
        "floatingLabel": boolean;
        "fullWidth": boolean;
        "hideNumberHandles": boolean;
        "hidePasswordText": string;
        "idElement": string;
        "inlineStyles": { [key: string]: string };
        "inputmode": string;
        "label": string;
        /**
          * Input mask configuration example {  mask: "00/00",  min: 0,  max: 0, }  The definitions that be used are: 0 - any digit a - any letter * - any char [] - make input optional {} - include fixed part in unmasked value ` - prevent symbols shif back  Patterns example: mask: +{7}(000)000-00-00 => value: +7(333)333-33-33 mask: 00/00 => value: 10/22
         */
        "maskOptions": any;
        "maxLength": number;
        "nameElement": string;
        "normalHelper": string;
        "pattern": string;
        "placeholder": string;
        "showMaxLength": boolean;
        "showPasswordText": string;
        "showPasswordToggle": boolean;
        "showTooltipOnChange": boolean;
        "state": 'normal' | 'disabled' | 'success' | 'error';
        "tabIndexElement": number;
        "tooltip": string;
        "type": string;
        "value": string;
    }
    interface PichinchaLink {
        "align"?: 'inherit' | 'left' | 'center' | 'right' | 'justify';
        "color"?: Colors;
        "disabled": boolean;
        "display": string;
        "href": string;
        /**
          * The color
         */
        "idElement": string;
        "inline_styles"?: object;
        "target": string;
        "variant": VariantText;
        "weight"?: 'normal' | 'bold';
    }
    interface PichinchaList {
        "color"?: COLORS;
        "data": ListItems[];
        "divided": boolean;
        "iconColor"?: COLORS;
        "iconWeightColor"?: WEIGHTCOLOR;
        "idElement": string;
        "variant": VARIANT;
        "weightColor"?: WEIGHTCOLOR;
    }
    interface PichinchaMessageBar {
        /**
          * Adjust in container
         */
        "adjustIn": boolean;
        /**
          * Show icon to close
         */
        "allowClose"?: boolean;
        /**
          * Autoclose the message-bar after x milliseconds
         */
        "autoClose"?: number;
        "icon": string;
        /**
          * Element id
         */
        "idElement"?: string;
        /**
          * Closed by default, if it's true shows the component
         */
        "open": boolean;
        /**
          * Can be: 'success', 'error', 'warning' or 'info' By default 'info' if not specified
         */
        "status": 'success' | 'error' | 'warning' | 'info';
        /**
          * Position absolute
         */
        "top"?: number;
        /**
          * Variant color
         */
        "variant"?: 'light' | 'normal';
    }
    interface PichinchaModal {
        "borderHeader": boolean;
        "disabledPrimaryButton": boolean;
        "idElement": string;
        "open": boolean;
        "primaryButtonLabel": string;
        "secondaryButtonLabel": string;
        "showCloseButton": boolean;
        "size": 'sm' | 'md' | 'lg';
    }
    interface PichinchaMultiselect {
        "countSelectedOptions": number;
        "errorHelper": string;
        "fullWidth": boolean;
        "idElement": string;
        "items": SelectItems[];
        "label": string;
        "normalHelper": string;
        "placeholder": string;
        "size": SIZE;
        "state": STATE;
        "tooltip": string;
    }
    interface PichinchaOtp {
        "backButtonLabel": string;
        "boxs": number;
        "contactDescription": string;
        "contactHelpLabel": string;
        "description": string;
        "disabled": boolean;
        "errorAlertText": string;
        "errorCode": '1' | '2' | '';
        "fullWidth": boolean;
        "hideBackButton": boolean;
        "nextButtonLabel": string;
        "showInfo": boolean;
        "stateButton": 'normal' | 'loading';
        "stateResend": 'loading' | 'success' | 'error' | '';
        "status": 'normal' | 'error';
        "textCodeSent": string;
        "textHideCode": string;
        "textResendCode": string;
        "textResendingCode": string;
        "textShowCode": string;
        "textShowHideCode": string;
        "timer": number;
        "timerText": string;
        "titleOtp": string;
        "typePassword": boolean;
    }
    interface PichinchaOtpInput {
        "boxs": number;
        "clearOtp": boolean;
        "disabled": boolean;
        "fullWidth": boolean;
        "status": 'normal' | 'error';
        "textInput": string;
        "type": string;
    }
    interface PichinchaOtpTimer {
        "errorCode": '1' | '2' | '';
        "stateResend": | 'loading'
    | 'success'
    | 'error'
    | '';
        "status": 'normal' | 'error';
        "textCodeSent": string;
        "textResendCode": string;
        "textResendingCode": string;
        "timer": number;
        "timerText": string;
    }
    interface PichinchaRadioButtom {
        "checked": boolean;
        "disabled": boolean;
        "error": boolean;
        /**
          * The color
         */
        "idElement": string;
        "nameElement": string;
        "offLabelClick": boolean;
        "value": string;
    }
    interface PichinchaReview {
        "authorDescription": string;
        "authorLastName": string;
        "authorName": string;
        "authorSrc"?: string;
        "mainComment": string;
        "mainTitle"?: string;
        "maxScore"?: number;
        "reviewComment": string;
        "reviewTitle"?: string;
        "score"?: number;
    }
    interface PichinchaSelect {
        /**
          * Change the behavior of the item list display
         */
        "dropUp": boolean;
        "errorHelper": string;
        /**
          * unique element
         */
        "idElement": string;
        /**
          * An array of items to be displayed
         */
        "items": SelectItem[];
        "label": string;
        "normalHelper": string;
        /**
          * Set placeholder 'Seleccione una opción' by default
         */
        "placeholder": string;
        /**
          * Sets the size 'medium' by default
         */
        "size": SIZE1;
        /**
          * Sets the state 'normal' by default
         */
        "state": STATE1;
    }
    interface PichinchaSelectorBox {
        "additionalTermPlaceholder": string;
        "additionalTermType": 'input' | 'button';
        "cancelButtonTextModal": string;
        "idElement": string;
        "isDisabled": boolean;
        "labelInputModal": string;
        "saveButtonTextModal": string;
        "terms": Term[];
        "termsRangeConfig": any;
        "unitOfTime": string;
        "unitOfTimePlural": string;
    }
    interface PichinchaSpinner {
        "background": string;
        "border": number;
        "color": string;
        "size": number;
    }
    interface PichinchaSwitch {
        "checked": boolean;
        "disabled": boolean;
        "error": boolean;
        "idElement": string;
        "labelBefore": boolean;
        "offLabelClick": boolean;
        "value": string;
    }
    interface PichinchaTab {
        "active": boolean;
        "iconName"?: string;
        "name": string;
        "tabsStyle": 'default' | 'primary' | 'secondary' | 'default-gray';
    }
    interface PichinchaTabContent {
        "active": boolean;
        "name": string;
    }
    interface PichinchaTable {
        "actions": Actions[];
        "headers": Header[];
        "rows": Row[];
        "showRowStatus": boolean;
        "sizeStart": number;
    }
    interface PichinchaTabs {
        "activetab": string;
        "bkg"?: 'white' | 'gray';
        "tabsStyle": 'default' | 'primary' | 'secondary' | 'default-gray';
    }
    interface PichinchaTestimonial {
        "items": string;
    }
    interface PichinchaTooltip {
        "position"?: 'top' | 'bottom' | 'left' | 'right';
        "text"?: string;
        "textAlign"?: 'left' | 'center' | 'right';
    }
    interface PichinchaTypography {
        "align"?: 'inherit' | 'left' | 'center' | 'right' | 'justify';
        "category"?: 'heading' | 'paragraphs' | 'amounts' | 'actions';
        "color"?: AllColorType | Colors;
        /**
          * Deprecated
         */
        "inline_styles"?: object;
        "subCategory"?: | 'hero'
    | 'h1'
    | 'h2'
    | 'h3'
    | 'title'
    | 'subtitle'
    | 'body'
    | 'caption'
    | 'legal'
    | 'primary'
    | 'seconday'
    | 'buttons';
        /**
          * Deprecated
         */
        "variant": VariantText;
        /**
          * Deprecated
         */
        "weight"?: 'normal' | 'bold';
        "weightCategory"?: | 'book'
    | 'book-slab'
    | 'semi-bold'
    | 'bold'
    | 'semi-bold-slab'
    | 'underline'
    | 'medium'
    | 'small'
    | 'default';
        /**
          * Deprecated
         */
        "weight_color"?: | '100'
    | '200'
    | '300'
    | '400'
    | '500'
    | '600'
    | '700'
    | '800'
    | '900';
    }
    interface PichinchaTypographyWebview {
        "align"?: 'inherit' | 'left' | 'center' | 'right' | 'justify';
        "ariaHidden": any;
        "ariaLabel": any;
        "color"?: Colors;
        "inline_styles"?: object;
        "variant": VariantWebviewsText;
        "weight"?: 'book' | 'semiBold' | 'medium';
        "weight_color"?: | '100'
    | '200'
    | '300'
    | '400'
    | '500'
    | '600'
    | '700'
    | '800'
    | '900';
    }
    interface RadioButtomContainer {
        "checked": string;
        "nameRadio": string;
    }
}
export interface MovilEmailCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMovilEmailElement;
}
export interface PichinchaAccordionCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPichinchaAccordionElement;
}
export interface PichinchaAccountSelectWebviewCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPichinchaAccountSelectWebviewElement;
}
export interface PichinchaAlertMessageCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPichinchaAlertMessageElement;
}
export interface PichinchaButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPichinchaButtonElement;
}
export interface PichinchaCallmebackCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPichinchaCallmebackElement;
}
export interface PichinchaCheckBoxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPichinchaCheckBoxElement;
}
export interface PichinchaErrorReloadWebviewCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPichinchaErrorReloadWebviewElement;
}
export interface PichinchaFeedbackCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPichinchaFeedbackElement;
}
export interface PichinchaHeaderWebviewCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPichinchaHeaderWebviewElement;
}
export interface PichinchaInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPichinchaInputElement;
}
export interface PichinchaInputWebviewCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPichinchaInputWebviewElement;
}
export interface PichinchaLinkCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPichinchaLinkElement;
}
export interface PichinchaMessageBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPichinchaMessageBarElement;
}
export interface PichinchaModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPichinchaModalElement;
}
export interface PichinchaMultiselectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPichinchaMultiselectElement;
}
export interface PichinchaOtpCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPichinchaOtpElement;
}
export interface PichinchaOtpInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPichinchaOtpInputElement;
}
export interface PichinchaOtpTimerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPichinchaOtpTimerElement;
}
export interface PichinchaRadioButtomCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPichinchaRadioButtomElement;
}
export interface PichinchaSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPichinchaSelectElement;
}
export interface PichinchaSelectorBoxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPichinchaSelectorBoxElement;
}
export interface PichinchaSwitchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPichinchaSwitchElement;
}
export interface PichinchaTabCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPichinchaTabElement;
}
export interface RadioButtomContainerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRadioButtomContainerElement;
}
declare global {
    interface HTMLActionTableElement extends Components.ActionTable, HTMLStencilElement {
    }
    var HTMLActionTableElement: {
        prototype: HTMLActionTableElement;
        new (): HTMLActionTableElement;
    };
    interface HTMLBadgeTableElement extends Components.BadgeTable, HTMLStencilElement {
    }
    var HTMLBadgeTableElement: {
        prototype: HTMLBadgeTableElement;
        new (): HTMLBadgeTableElement;
    };
    interface HTMLMovilEmailElement extends Components.MovilEmail, HTMLStencilElement {
    }
    var HTMLMovilEmailElement: {
        prototype: HTMLMovilEmailElement;
        new (): HTMLMovilEmailElement;
    };
    interface HTMLPichinchaAccordionElement extends Components.PichinchaAccordion, HTMLStencilElement {
    }
    var HTMLPichinchaAccordionElement: {
        prototype: HTMLPichinchaAccordionElement;
        new (): HTMLPichinchaAccordionElement;
    };
    interface HTMLPichinchaAccountSelectWebviewElement extends Components.PichinchaAccountSelectWebview, HTMLStencilElement {
    }
    var HTMLPichinchaAccountSelectWebviewElement: {
        prototype: HTMLPichinchaAccountSelectWebviewElement;
        new (): HTMLPichinchaAccountSelectWebviewElement;
    };
    interface HTMLPichinchaAlertMessageElement extends Components.PichinchaAlertMessage, HTMLStencilElement {
    }
    var HTMLPichinchaAlertMessageElement: {
        prototype: HTMLPichinchaAlertMessageElement;
        new (): HTMLPichinchaAlertMessageElement;
    };
    interface HTMLPichinchaAvatarElement extends Components.PichinchaAvatar, HTMLStencilElement {
    }
    var HTMLPichinchaAvatarElement: {
        prototype: HTMLPichinchaAvatarElement;
        new (): HTMLPichinchaAvatarElement;
    };
    interface HTMLPichinchaBrandElement extends Components.PichinchaBrand, HTMLStencilElement {
    }
    var HTMLPichinchaBrandElement: {
        prototype: HTMLPichinchaBrandElement;
        new (): HTMLPichinchaBrandElement;
    };
    interface HTMLPichinchaButtonElement extends Components.PichinchaButton, HTMLStencilElement {
    }
    var HTMLPichinchaButtonElement: {
        prototype: HTMLPichinchaButtonElement;
        new (): HTMLPichinchaButtonElement;
    };
    interface HTMLPichinchaCallmebackElement extends Components.PichinchaCallmeback, HTMLStencilElement {
    }
    var HTMLPichinchaCallmebackElement: {
        prototype: HTMLPichinchaCallmebackElement;
        new (): HTMLPichinchaCallmebackElement;
    };
    interface HTMLPichinchaCarouselElement extends Components.PichinchaCarousel, HTMLStencilElement {
    }
    var HTMLPichinchaCarouselElement: {
        prototype: HTMLPichinchaCarouselElement;
        new (): HTMLPichinchaCarouselElement;
    };
    interface HTMLPichinchaCarouselItemElement extends Components.PichinchaCarouselItem, HTMLStencilElement {
    }
    var HTMLPichinchaCarouselItemElement: {
        prototype: HTMLPichinchaCarouselItemElement;
        new (): HTMLPichinchaCarouselItemElement;
    };
    interface HTMLPichinchaCheckBoxElement extends Components.PichinchaCheckBox, HTMLStencilElement {
    }
    var HTMLPichinchaCheckBoxElement: {
        prototype: HTMLPichinchaCheckBoxElement;
        new (): HTMLPichinchaCheckBoxElement;
    };
    interface HTMLPichinchaErrorReloadWebviewElement extends Components.PichinchaErrorReloadWebview, HTMLStencilElement {
    }
    var HTMLPichinchaErrorReloadWebviewElement: {
        prototype: HTMLPichinchaErrorReloadWebviewElement;
        new (): HTMLPichinchaErrorReloadWebviewElement;
    };
    interface HTMLPichinchaFeedbackElement extends Components.PichinchaFeedback, HTMLStencilElement {
    }
    var HTMLPichinchaFeedbackElement: {
        prototype: HTMLPichinchaFeedbackElement;
        new (): HTMLPichinchaFeedbackElement;
    };
    interface HTMLPichinchaFeedbackWebviewElement extends Components.PichinchaFeedbackWebview, HTMLStencilElement {
    }
    var HTMLPichinchaFeedbackWebviewElement: {
        prototype: HTMLPichinchaFeedbackWebviewElement;
        new (): HTMLPichinchaFeedbackWebviewElement;
    };
    interface HTMLPichinchaGridElement extends Components.PichinchaGrid, HTMLStencilElement {
    }
    var HTMLPichinchaGridElement: {
        prototype: HTMLPichinchaGridElement;
        new (): HTMLPichinchaGridElement;
    };
    interface HTMLPichinchaGridV2Element extends Components.PichinchaGridV2, HTMLStencilElement {
    }
    var HTMLPichinchaGridV2Element: {
        prototype: HTMLPichinchaGridV2Element;
        new (): HTMLPichinchaGridV2Element;
    };
    interface HTMLPichinchaHeaderWebviewElement extends Components.PichinchaHeaderWebview, HTMLStencilElement {
    }
    var HTMLPichinchaHeaderWebviewElement: {
        prototype: HTMLPichinchaHeaderWebviewElement;
        new (): HTMLPichinchaHeaderWebviewElement;
    };
    interface HTMLPichinchaIconElement extends Components.PichinchaIcon, HTMLStencilElement {
    }
    var HTMLPichinchaIconElement: {
        prototype: HTMLPichinchaIconElement;
        new (): HTMLPichinchaIconElement;
    };
    interface HTMLPichinchaInputElement extends Components.PichinchaInput, HTMLStencilElement {
    }
    var HTMLPichinchaInputElement: {
        prototype: HTMLPichinchaInputElement;
        new (): HTMLPichinchaInputElement;
    };
    interface HTMLPichinchaInputWebviewElement extends Components.PichinchaInputWebview, HTMLStencilElement {
    }
    var HTMLPichinchaInputWebviewElement: {
        prototype: HTMLPichinchaInputWebviewElement;
        new (): HTMLPichinchaInputWebviewElement;
    };
    interface HTMLPichinchaLinkElement extends Components.PichinchaLink, HTMLStencilElement {
    }
    var HTMLPichinchaLinkElement: {
        prototype: HTMLPichinchaLinkElement;
        new (): HTMLPichinchaLinkElement;
    };
    interface HTMLPichinchaListElement extends Components.PichinchaList, HTMLStencilElement {
    }
    var HTMLPichinchaListElement: {
        prototype: HTMLPichinchaListElement;
        new (): HTMLPichinchaListElement;
    };
    interface HTMLPichinchaMessageBarElement extends Components.PichinchaMessageBar, HTMLStencilElement {
    }
    var HTMLPichinchaMessageBarElement: {
        prototype: HTMLPichinchaMessageBarElement;
        new (): HTMLPichinchaMessageBarElement;
    };
    interface HTMLPichinchaModalElement extends Components.PichinchaModal, HTMLStencilElement {
    }
    var HTMLPichinchaModalElement: {
        prototype: HTMLPichinchaModalElement;
        new (): HTMLPichinchaModalElement;
    };
    interface HTMLPichinchaMultiselectElement extends Components.PichinchaMultiselect, HTMLStencilElement {
    }
    var HTMLPichinchaMultiselectElement: {
        prototype: HTMLPichinchaMultiselectElement;
        new (): HTMLPichinchaMultiselectElement;
    };
    interface HTMLPichinchaOtpElement extends Components.PichinchaOtp, HTMLStencilElement {
    }
    var HTMLPichinchaOtpElement: {
        prototype: HTMLPichinchaOtpElement;
        new (): HTMLPichinchaOtpElement;
    };
    interface HTMLPichinchaOtpInputElement extends Components.PichinchaOtpInput, HTMLStencilElement {
    }
    var HTMLPichinchaOtpInputElement: {
        prototype: HTMLPichinchaOtpInputElement;
        new (): HTMLPichinchaOtpInputElement;
    };
    interface HTMLPichinchaOtpTimerElement extends Components.PichinchaOtpTimer, HTMLStencilElement {
    }
    var HTMLPichinchaOtpTimerElement: {
        prototype: HTMLPichinchaOtpTimerElement;
        new (): HTMLPichinchaOtpTimerElement;
    };
    interface HTMLPichinchaRadioButtomElement extends Components.PichinchaRadioButtom, HTMLStencilElement {
    }
    var HTMLPichinchaRadioButtomElement: {
        prototype: HTMLPichinchaRadioButtomElement;
        new (): HTMLPichinchaRadioButtomElement;
    };
    interface HTMLPichinchaReviewElement extends Components.PichinchaReview, HTMLStencilElement {
    }
    var HTMLPichinchaReviewElement: {
        prototype: HTMLPichinchaReviewElement;
        new (): HTMLPichinchaReviewElement;
    };
    interface HTMLPichinchaSelectElement extends Components.PichinchaSelect, HTMLStencilElement {
    }
    var HTMLPichinchaSelectElement: {
        prototype: HTMLPichinchaSelectElement;
        new (): HTMLPichinchaSelectElement;
    };
    interface HTMLPichinchaSelectorBoxElement extends Components.PichinchaSelectorBox, HTMLStencilElement {
    }
    var HTMLPichinchaSelectorBoxElement: {
        prototype: HTMLPichinchaSelectorBoxElement;
        new (): HTMLPichinchaSelectorBoxElement;
    };
    interface HTMLPichinchaSpinnerElement extends Components.PichinchaSpinner, HTMLStencilElement {
    }
    var HTMLPichinchaSpinnerElement: {
        prototype: HTMLPichinchaSpinnerElement;
        new (): HTMLPichinchaSpinnerElement;
    };
    interface HTMLPichinchaSwitchElement extends Components.PichinchaSwitch, HTMLStencilElement {
    }
    var HTMLPichinchaSwitchElement: {
        prototype: HTMLPichinchaSwitchElement;
        new (): HTMLPichinchaSwitchElement;
    };
    interface HTMLPichinchaTabElement extends Components.PichinchaTab, HTMLStencilElement {
    }
    var HTMLPichinchaTabElement: {
        prototype: HTMLPichinchaTabElement;
        new (): HTMLPichinchaTabElement;
    };
    interface HTMLPichinchaTabContentElement extends Components.PichinchaTabContent, HTMLStencilElement {
    }
    var HTMLPichinchaTabContentElement: {
        prototype: HTMLPichinchaTabContentElement;
        new (): HTMLPichinchaTabContentElement;
    };
    interface HTMLPichinchaTableElement extends Components.PichinchaTable, HTMLStencilElement {
    }
    var HTMLPichinchaTableElement: {
        prototype: HTMLPichinchaTableElement;
        new (): HTMLPichinchaTableElement;
    };
    interface HTMLPichinchaTabsElement extends Components.PichinchaTabs, HTMLStencilElement {
    }
    var HTMLPichinchaTabsElement: {
        prototype: HTMLPichinchaTabsElement;
        new (): HTMLPichinchaTabsElement;
    };
    interface HTMLPichinchaTestimonialElement extends Components.PichinchaTestimonial, HTMLStencilElement {
    }
    var HTMLPichinchaTestimonialElement: {
        prototype: HTMLPichinchaTestimonialElement;
        new (): HTMLPichinchaTestimonialElement;
    };
    interface HTMLPichinchaTooltipElement extends Components.PichinchaTooltip, HTMLStencilElement {
    }
    var HTMLPichinchaTooltipElement: {
        prototype: HTMLPichinchaTooltipElement;
        new (): HTMLPichinchaTooltipElement;
    };
    interface HTMLPichinchaTypographyElement extends Components.PichinchaTypography, HTMLStencilElement {
    }
    var HTMLPichinchaTypographyElement: {
        prototype: HTMLPichinchaTypographyElement;
        new (): HTMLPichinchaTypographyElement;
    };
    interface HTMLPichinchaTypographyWebviewElement extends Components.PichinchaTypographyWebview, HTMLStencilElement {
    }
    var HTMLPichinchaTypographyWebviewElement: {
        prototype: HTMLPichinchaTypographyWebviewElement;
        new (): HTMLPichinchaTypographyWebviewElement;
    };
    interface HTMLRadioButtomContainerElement extends Components.RadioButtomContainer, HTMLStencilElement {
    }
    var HTMLRadioButtomContainerElement: {
        prototype: HTMLRadioButtomContainerElement;
        new (): HTMLRadioButtomContainerElement;
    };
    interface HTMLElementTagNameMap {
        "action-table": HTMLActionTableElement;
        "badge-table": HTMLBadgeTableElement;
        "movil-email": HTMLMovilEmailElement;
        "pichincha-accordion": HTMLPichinchaAccordionElement;
        "pichincha-account-select-webview": HTMLPichinchaAccountSelectWebviewElement;
        "pichincha-alert-message": HTMLPichinchaAlertMessageElement;
        "pichincha-avatar": HTMLPichinchaAvatarElement;
        "pichincha-brand": HTMLPichinchaBrandElement;
        "pichincha-button": HTMLPichinchaButtonElement;
        "pichincha-callmeback": HTMLPichinchaCallmebackElement;
        "pichincha-carousel": HTMLPichinchaCarouselElement;
        "pichincha-carousel-item": HTMLPichinchaCarouselItemElement;
        "pichincha-check-box": HTMLPichinchaCheckBoxElement;
        "pichincha-error-reload-webview": HTMLPichinchaErrorReloadWebviewElement;
        "pichincha-feedback": HTMLPichinchaFeedbackElement;
        "pichincha-feedback-webview": HTMLPichinchaFeedbackWebviewElement;
        "pichincha-grid": HTMLPichinchaGridElement;
        "pichincha-grid-v2": HTMLPichinchaGridV2Element;
        "pichincha-header-webview": HTMLPichinchaHeaderWebviewElement;
        "pichincha-icon": HTMLPichinchaIconElement;
        "pichincha-input": HTMLPichinchaInputElement;
        "pichincha-input-webview": HTMLPichinchaInputWebviewElement;
        "pichincha-link": HTMLPichinchaLinkElement;
        "pichincha-list": HTMLPichinchaListElement;
        "pichincha-message-bar": HTMLPichinchaMessageBarElement;
        "pichincha-modal": HTMLPichinchaModalElement;
        "pichincha-multiselect": HTMLPichinchaMultiselectElement;
        "pichincha-otp": HTMLPichinchaOtpElement;
        "pichincha-otp-input": HTMLPichinchaOtpInputElement;
        "pichincha-otp-timer": HTMLPichinchaOtpTimerElement;
        "pichincha-radio-buttom": HTMLPichinchaRadioButtomElement;
        "pichincha-review": HTMLPichinchaReviewElement;
        "pichincha-select": HTMLPichinchaSelectElement;
        "pichincha-selector-box": HTMLPichinchaSelectorBoxElement;
        "pichincha-spinner": HTMLPichinchaSpinnerElement;
        "pichincha-switch": HTMLPichinchaSwitchElement;
        "pichincha-tab": HTMLPichinchaTabElement;
        "pichincha-tab-content": HTMLPichinchaTabContentElement;
        "pichincha-table": HTMLPichinchaTableElement;
        "pichincha-tabs": HTMLPichinchaTabsElement;
        "pichincha-testimonial": HTMLPichinchaTestimonialElement;
        "pichincha-tooltip": HTMLPichinchaTooltipElement;
        "pichincha-typography": HTMLPichinchaTypographyElement;
        "pichincha-typography-webview": HTMLPichinchaTypographyWebviewElement;
        "radio-buttom-container": HTMLRadioButtomContainerElement;
    }
}
declare namespace LocalJSX {
    interface ActionTable {
        "actions"?: Actions[];
        "indexRow"?: number;
        "lastRow"?: number;
        "row"?: Row;
        "status"?: string;
    }
    interface BadgeTable {
        "row"?: Row;
        "status"?: string;
    }
    interface MovilEmail {
        "onClickMovilEmail"?: (event: MovilEmailCustomEvent<any>) => void;
        "value"?: string;
    }
    interface PichinchaAccordion {
        "description"?: string;
        /**
          * index of accordion item from top to bottom
         */
        "index"?: number;
        /**
          * The mutation observer config to listen for content changes in the accordion item
         */
        "mutationObserverConfig"?: { childList: boolean; subtree: boolean; };
        "name"?: string;
        /**
          * triggered when the content of the accordion item changes
         */
        "onContentChanged"?: (event: PichinchaAccordionCustomEvent<any>) => void;
        /**
          * triggered when the accordion item is opened
         */
        "onOpenEvent"?: (event: PichinchaAccordionCustomEvent<any>) => void;
        /**
          * accordion item is open or opening (css transition)
         */
        "openAccordion"?: boolean;
    }
    interface PichinchaAccountSelectWebview {
        /**
          * Account name. E.g. "Cta. Ahorros". Position top-left
         */
        "accountName"?: string;
        /**
          * Account number. Position bottom-left
         */
        "accountNumber"?: string;
        /**
          * Account number. Position bottom-right
         */
        "amount"?: string;
        /**
          * Amount Label. E.g. "Saldo disponible". Position top-right
         */
        "amountLabel"?: string;
        /**
          * Screen reader label
         */
        "ariaLabel"?: string;
        /**
          * Id of the element
         */
        "idElement"?: string;
        /**
          * Event emmited when component is pressed
         */
        "onIpress"?: (event: PichinchaAccountSelectWebviewCustomEvent<any>) => void;
    }
    interface PichinchaAlertMessage {
        /**
          * Text for the Accept Button
         */
        "acceptButtonText"?: string;
        /**
          * Adjust in container
         */
        "adjustIn"?: boolean;
        /**
          * Alert message title string to show
         */
        "alertTitle"?: string;
        /**
          * Show icon to close
         */
        "allowClose"?: boolean;
        /**
          * Text for the Cancel Button
         */
        "cancelButtonText"?: string;
        /**
          * Close the alert-message after x milliseconds
         */
        "closeTime"?: number;
        /**
          * Alert will show a valid Icon
         */
        "hasIcon"?: boolean;
        /**
          * Icon to show in message
         */
        "icon"?: string;
        /**
          * Element id
         */
        "idElement"?: string;
        "onClickAccept"?: (event: PichinchaAlertMessageCustomEvent<any>) => void;
        "onClickCancel"?: (event: PichinchaAlertMessageCustomEvent<any>) => void;
        "onCloseMessage"?: (event: PichinchaAlertMessageCustomEvent<any>) => void;
        /**
          * Closed by default, if it's true shows the component
         */
        "open"?: boolean;
        /**
          * Can be: 'success', 'error', 'warning' or 'info' By default 'info' if not specified
         */
        "status"?: 'success' | 'error' | 'warning' | 'info';
        /**
          * Position absolute
         */
        "top"?: number;
    }
    interface PichinchaAvatar {
        "name"?: string;
        "size"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl' | 'xxl';
        "src"?: string;
        "type"?: | 'image'
    | 'icon'
    | 'name';
    }
    interface PichinchaBrand {
        "color"?: "primary" | "white" | "black" | "yellow" | "blue";
        "height"?: number;
        "type"?: "logo" | "emblem";
        "width"?: number;
    }
    interface PichinchaButton {
        "ariaLabel"?: any;
        /**
          * The color
         */
        "color"?: | 'primary'
    | 'secondary'
    | 'complementary'
    | 'tertiary'
    | 'destructive';
        "disabled"?: boolean;
        "href"?: string;
        "iconName"?: string;
        "iconNameRight"?: string;
        "iconType"?: | '--outlined'
    | '--round'
    | '--sharp'
    | '--two-tone';
        "idelement"?: string;
        "loading"?: boolean;
        "onClickbutton"?: (event: PichinchaButtonCustomEvent<any>) => void;
        "onlyIcon"?: boolean;
        "size"?: 'medium' | 'small' | 'large' | 'extra-large';
        "tabIndexInner"?: number;
        "type"?: string;
        "value"?: string;
    }
    interface PichinchaCallmeback {
        "buttonText"?: string;
        "confirmDescription"?: string;
        "confirmPrimaryButton"?: string;
        "confirmSecondaryButton"?: string;
        "confirmTitle"?: string;
        "contactName"?: string;
        "contactNumber"?: string;
        "disabledButtonUpdate"?: boolean;
        "errorDescription"?: string;
        "errorPrimaryButton"?: string;
        "errorTitle"?: string;
        "hidden"?: boolean;
        "loadingButton"?: boolean;
        "onClickCallMeBack"?: (event: PichinchaCallmebackCustomEvent<any>) => void;
        "onClickCloseModal"?: (event: PichinchaCallmebackCustomEvent<any>) => void;
        "onClickErrorButton"?: (event: PichinchaCallmebackCustomEvent<any>) => void;
        "onClickFloatButton"?: (event: PichinchaCallmebackCustomEvent<any>) => void;
        "onClickSuccessButton"?: (event: PichinchaCallmebackCustomEvent<any>) => void;
        "onClickUpdateButton"?: (event: PichinchaCallmebackCustomEvent<any>) => void;
        "onOverlay-event"?: (event: PichinchaCallmebackCustomEvent<any>) => void;
        "showText"?: boolean;
        "showUpdate"?: boolean;
        "step"?: 'confirm' | 'success' | 'update' | 'error';
        "successDescription"?: string;
        "successPrimaryButton"?: string;
        "successTitle"?: string;
        "updateDescription"?: string;
        "updatePrimaryButton"?: string;
        "updateSecondaryButton"?: string;
        "updateTitle"?: string;
    }
    interface PichinchaCarousel {
        "timeAutoPlay"?: number;
    }
    interface PichinchaCarouselItem {
        "isActive"?: boolean;
    }
    interface PichinchaCheckBox {
        "checked"?: boolean;
        "disabled"?: boolean;
        "error"?: boolean;
        /**
          * The color
         */
        "idElement"?: string;
        "nameElement"?: string;
        "offLabelClick"?: boolean;
        "onClickCheck"?: (event: PichinchaCheckBoxCustomEvent<any>) => void;
        "typeCheck"?: string;
        "value"?: string;
    }
    interface PichinchaErrorReloadWebview {
        "ariaHidden"?: string | undefined;
        /**
          * Description in the component
         */
        "description"?: string;
        /**
          * Id of the element
         */
        "idElement"?: string;
        /**
          * Event emitted when the icon or the text link are clicked
         */
        "onIreload"?: (event: PichinchaErrorReloadWebviewCustomEvent<any>) => void;
        /**
          * Text link in the component
         */
        "reloadText"?: string;
    }
    interface PichinchaFeedback {
        "img"?: string;
        "onClickButton"?: (event: PichinchaFeedbackCustomEvent<any>) => void;
        "showButton"?: boolean;
        "title"?: string;
    }
    interface PichinchaFeedbackWebview {
        /**
          * Screen reader label
         */
        "ariaLabel"?: string;
        /**
          * Description of the component
         */
        "description"?: string;
        /**
          * Id of the element
         */
        "idElement"?: string;
        /**
          * State of the feedback. It changes the icon that is displayed
         */
        "state"?: 'error' | 'warning' | 'success' | 'info';
        /**
          * Title of the component
         */
        "subtitle"?: string;
        /**
          * Type of feedback. Can be Title or Subtitle
         */
        "variant"?: 'subtitle' | 'title';
    }
    interface PichinchaGrid {
        "align_content"?: AlignContent;
        "align_items"?: AlignItems;
        "container"?: boolean;
        "direction"?: Direction;
        "item"?: boolean;
        "justify"?: Justify;
        "lg"?: Size;
        "md"?: Size;
        "sm"?: Size;
        "spacing"?: Size;
        "wrap"?: Wrap;
        "xl"?: Size;
        "xs"?: Size;
    }
    interface PichinchaGridV2 {
        "align_content"?: AlignContent;
        "align_items"?: AlignItems;
        "container"?: boolean;
        "direction"?: Direction;
        "isDefaultMargin"?: boolean;
        "item"?: boolean;
        "justify"?: Justify;
        "lg"?: Size;
        "md"?: Size;
        "sm"?: Size;
        "wrap"?: Wrap;
        "xl"?: Size;
        "xs"?: Size;
    }
    interface PichinchaHeaderWebview {
        /**
          * Hide from screen reader the header
         */
        "accesibilityHidden"?: string;
        /**
          * Title read by screen reader
         */
        "ariaTitle"?: string | undefined;
        /**
          * Event emitted when header button is pressed
         */
        "onBackButtonPress"?: (event: PichinchaHeaderWebviewCustomEvent<any>) => void;
        "showBreadcrumb"?: boolean;
        /**
          * Title in the header
         */
        "textTitle"?: string;
    }
    interface PichinchaIcon {
        /**
          * The color of the icon
         */
        "color"?: Colors;
        /**
          * Inline styles for the icons container
         */
        "inline_styles"?: { [key: string]: string };
        /**
          * The size of the icon
         */
        "size"?: string;
        /**
          * The weight of the icon
         */
        "type"?: IconTypes;
        /**
          * The weight of the icon
         */
        "weight_color"?: | '100'
    | '200'
    | '300'
    | '400'
    | '500'
    | '600'
    | '700'
    | '800'
    | '900';
    }
    interface PichinchaInput {
        "autoComplete"?: boolean;
        "autofocus"?: boolean;
        "class"?: string;
        "controlEvent"?: boolean;
        "errorHelper"?: string;
        "filterRegex"?: string;
        "floatingLabel"?: boolean;
        "fullWidth"?: boolean;
        "hideNumberHandles"?: boolean;
        "hidePasswordText"?: string;
        "idElement"?: string;
        "inlineStyles"?: { [key: string]: string };
        "inputmode"?: string;
        "label"?: string;
        "maxLength"?: number;
        "nameElement"?: string;
        "normalHelper"?: string;
        "onEventValue"?: (event: PichinchaInputCustomEvent<any>) => void;
        "onIPaste"?: (event: PichinchaInputCustomEvent<any>) => void;
        "onIblur"?: (event: PichinchaInputCustomEvent<any>) => void;
        "onIchange"?: (event: PichinchaInputCustomEvent<any>) => void;
        "onIfocus"?: (event: PichinchaInputCustomEvent<any>) => void;
        "onIkeydown"?: (event: PichinchaInputCustomEvent<any>) => void;
        "onIkeypress"?: (event: PichinchaInputCustomEvent<any>) => void;
        "onIkeyup"?: (event: PichinchaInputCustomEvent<any>) => void;
        "onPasswordToggleMouseDown"?: (event: PichinchaInputCustomEvent<any>) => void;
        "onPasswordToggleMouseLeave"?: (event: PichinchaInputCustomEvent<any>) => void;
        "onPasswordToggleMouseUp"?: (event: PichinchaInputCustomEvent<any>) => void;
        "onPasswordToggleTouchCancel"?: (event: PichinchaInputCustomEvent<any>) => void;
        "onPasswordToggleTouchEnd"?: (event: PichinchaInputCustomEvent<any>) => void;
        "pattern"?: string;
        "placeholder"?: string;
        "showIconStatus"?: boolean;
        "showMaxLength"?: boolean;
        "showPasswordText"?: string;
        "showPasswordToggle"?: boolean;
        "showTooltipOnChange"?: boolean;
        "size"?: 'extra-small' | 'small' | 'medium' | 'large';
        "state"?: 'normal' | 'disabled' | 'success' | 'error';
        "tabIndexElement"?: number;
        "tooltip"?: string;
        "tooltipBody"?: any;
        "type"?: string;
        "value"?: string;
    }
    interface PichinchaInputWebview {
        /**
          * Screen reader label
         */
        "ariaLabel"?: any;
        /**
          * Screen reader role description
         */
        "ariaRoleDescription"?: any;
        "autoComplete"?: boolean;
        "autofocus"?: boolean;
        /**
          * Lost focus to hide soft keyboard in mobile browsers
         */
        "blurOnEnter"?: boolean;
        "class"?: string;
        "controlEvent"?: boolean;
        "errorHelper"?: string;
        "filterRegex"?: string;
        "floatingLabel"?: boolean;
        "fullWidth"?: boolean;
        "hideNumberHandles"?: boolean;
        "hidePasswordText"?: string;
        "idElement"?: string;
        "inlineStyles"?: { [key: string]: string };
        "inputmode"?: string;
        "label"?: string;
        /**
          * Input mask configuration example {  mask: "00/00",  min: 0,  max: 0, }  The definitions that be used are: 0 - any digit a - any letter * - any char [] - make input optional {} - include fixed part in unmasked value ` - prevent symbols shif back  Patterns example: mask: +{7}(000)000-00-00 => value: +7(333)333-33-33 mask: 00/00 => value: 10/22
         */
        "maskOptions"?: any;
        "maxLength"?: number;
        "nameElement"?: string;
        "normalHelper"?: string;
        "onEventValue"?: (event: PichinchaInputWebviewCustomEvent<any>) => void;
        "onIPaste"?: (event: PichinchaInputWebviewCustomEvent<any>) => void;
        "onIblur"?: (event: PichinchaInputWebviewCustomEvent<any>) => void;
        "onIchange"?: (event: PichinchaInputWebviewCustomEvent<any>) => void;
        "onIfocus"?: (event: PichinchaInputWebviewCustomEvent<any>) => void;
        "onIkeydown"?: (event: PichinchaInputWebviewCustomEvent<any>) => void;
        "onIkeypress"?: (event: PichinchaInputWebviewCustomEvent<any>) => void;
        "onIkeyup"?: (event: PichinchaInputWebviewCustomEvent<any>) => void;
        /**
          * Event emmitted with unmasked value and input mask config
         */
        "onImaskedValueChange"?: (event: PichinchaInputWebviewCustomEvent<any>) => void;
        "onPasswordToggleMouseDown"?: (event: PichinchaInputWebviewCustomEvent<any>) => void;
        "onPasswordToggleMouseLeave"?: (event: PichinchaInputWebviewCustomEvent<any>) => void;
        "onPasswordToggleMouseUp"?: (event: PichinchaInputWebviewCustomEvent<any>) => void;
        "onPasswordToggleTouchCancel"?: (event: PichinchaInputWebviewCustomEvent<any>) => void;
        "onPasswordToggleTouchEnd"?: (event: PichinchaInputWebviewCustomEvent<any>) => void;
        "pattern"?: string;
        "placeholder"?: string;
        "showMaxLength"?: boolean;
        "showPasswordText"?: string;
        "showPasswordToggle"?: boolean;
        "showTooltipOnChange"?: boolean;
        "state"?: 'normal' | 'disabled' | 'success' | 'error';
        "tabIndexElement"?: number;
        "tooltip"?: string;
        "type"?: string;
        "value"?: string;
    }
    interface PichinchaLink {
        "align"?: 'inherit' | 'left' | 'center' | 'right' | 'justify';
        "color"?: Colors;
        "disabled"?: boolean;
        "display"?: string;
        "href"?: string;
        /**
          * The color
         */
        "idElement"?: string;
        "inline_styles"?: object;
        "onClicklink"?: (event: PichinchaLinkCustomEvent<any>) => void;
        "onTouchStartLink"?: (event: PichinchaLinkCustomEvent<any>) => void;
        "target"?: string;
        "variant"?: VariantText;
        "weight"?: 'normal' | 'bold';
    }
    interface PichinchaList {
        "color"?: COLORS;
        "data"?: ListItems[];
        "divided"?: boolean;
        "iconColor"?: COLORS;
        "iconWeightColor"?: WEIGHTCOLOR;
        "idElement"?: string;
        "variant"?: VARIANT;
        "weightColor"?: WEIGHTCOLOR;
    }
    interface PichinchaMessageBar {
        /**
          * Adjust in container
         */
        "adjustIn"?: boolean;
        /**
          * Show icon to close
         */
        "allowClose"?: boolean;
        /**
          * Autoclose the message-bar after x milliseconds
         */
        "autoClose"?: number;
        "icon"?: string;
        /**
          * Element id
         */
        "idElement"?: string;
        "onCloseMessage"?: (event: PichinchaMessageBarCustomEvent<any>) => void;
        /**
          * Closed by default, if it's true shows the component
         */
        "open"?: boolean;
        /**
          * Can be: 'success', 'error', 'warning' or 'info' By default 'info' if not specified
         */
        "status"?: 'success' | 'error' | 'warning' | 'info';
        /**
          * Position absolute
         */
        "top"?: number;
        /**
          * Variant color
         */
        "variant"?: 'light' | 'normal';
    }
    interface PichinchaModal {
        "borderHeader"?: boolean;
        "disabledPrimaryButton"?: boolean;
        "idElement"?: string;
        "onClickPrimaryButton"?: (event: PichinchaModalCustomEvent<any>) => void;
        "onClickSecondaryButton"?: (event: PichinchaModalCustomEvent<any>) => void;
        "open"?: boolean;
        "primaryButtonLabel"?: string;
        "secondaryButtonLabel"?: string;
        "showCloseButton"?: boolean;
        "size"?: 'sm' | 'md' | 'lg';
    }
    interface PichinchaMultiselect {
        "countSelectedOptions"?: number;
        "errorHelper"?: string;
        "fullWidth"?: boolean;
        "idElement"?: string;
        "items"?: SelectItems[];
        "label"?: string;
        "normalHelper"?: string;
        "onClickedItem"?: (event: PichinchaMultiselectCustomEvent<any>) => void;
        "placeholder"?: string;
        "size"?: SIZE;
        "state"?: STATE;
        "tooltip"?: string;
    }
    interface PichinchaOtp {
        "backButtonLabel"?: string;
        "boxs"?: number;
        "contactDescription"?: string;
        "contactHelpLabel"?: string;
        "description"?: string;
        "disabled"?: boolean;
        "errorAlertText"?: string;
        "errorCode"?: '1' | '2' | '';
        "fullWidth"?: boolean;
        "hideBackButton"?: boolean;
        "nextButtonLabel"?: string;
        "onClickContinue"?: (event: PichinchaOtpCustomEvent<any>) => void;
        "onClickGoBack"?: (event: PichinchaOtpCustomEvent<any>) => void;
        "onClickResend"?: (event: PichinchaOtpCustomEvent<any>) => void;
        "onTimeExpired"?: (event: PichinchaOtpCustomEvent<any>) => void;
        "showInfo"?: boolean;
        "stateButton"?: 'normal' | 'loading';
        "stateResend"?: 'loading' | 'success' | 'error' | '';
        "status"?: 'normal' | 'error';
        "textCodeSent"?: string;
        "textHideCode"?: string;
        "textResendCode"?: string;
        "textResendingCode"?: string;
        "textShowCode"?: string;
        "textShowHideCode"?: string;
        "timer"?: number;
        "timerText"?: string;
        "titleOtp"?: string;
        "typePassword"?: boolean;
    }
    interface PichinchaOtpInput {
        "boxs"?: number;
        "clearOtp"?: boolean;
        "disabled"?: boolean;
        "fullWidth"?: boolean;
        "onEventChangeInputOtp"?: (event: PichinchaOtpInputCustomEvent<any>) => void;
        "status"?: 'normal' | 'error';
        "textInput"?: string;
        "type"?: string;
    }
    interface PichinchaOtpTimer {
        "errorCode"?: '1' | '2' | '';
        "onClickResendCode"?: (event: PichinchaOtpTimerCustomEvent<any>) => void;
        "stateResend"?: | 'loading'
    | 'success'
    | 'error'
    | '';
        "status"?: 'normal' | 'error';
        "textCodeSent"?: string;
        "textResendCode"?: string;
        "textResendingCode"?: string;
        "timer"?: number;
        "timerText"?: string;
    }
    interface PichinchaRadioButtom {
        "checked"?: boolean;
        "disabled"?: boolean;
        "error"?: boolean;
        /**
          * The color
         */
        "idElement"?: string;
        "nameElement"?: string;
        "offLabelClick"?: boolean;
        "onClickRadio"?: (event: PichinchaRadioButtomCustomEvent<any>) => void;
        "value"?: string;
    }
    interface PichinchaReview {
        "authorDescription"?: string;
        "authorLastName"?: string;
        "authorName"?: string;
        "authorSrc"?: string;
        "mainComment"?: string;
        "mainTitle"?: string;
        "maxScore"?: number;
        "reviewComment"?: string;
        "reviewTitle"?: string;
        "score"?: number;
    }
    interface PichinchaSelect {
        /**
          * Change the behavior of the item list display
         */
        "dropUp"?: boolean;
        "errorHelper"?: string;
        /**
          * unique element
         */
        "idElement"?: string;
        /**
          * An array of items to be displayed
         */
        "items"?: SelectItem[];
        "label"?: string;
        "normalHelper"?: string;
        "onClickedItem"?: (event: PichinchaSelectCustomEvent<any>) => void;
        /**
          * Set placeholder 'Seleccione una opción' by default
         */
        "placeholder"?: string;
        /**
          * Sets the size 'medium' by default
         */
        "size"?: SIZE1;
        /**
          * Sets the state 'normal' by default
         */
        "state"?: STATE1;
    }
    interface PichinchaSelectorBox {
        "additionalTermPlaceholder"?: string;
        "additionalTermType"?: 'input' | 'button';
        "cancelButtonTextModal"?: string;
        "idElement"?: string;
        "isDisabled"?: boolean;
        "labelInputModal"?: string;
        "onTermChange"?: (event: PichinchaSelectorBoxCustomEvent<any>) => void;
        "saveButtonTextModal"?: string;
        "terms"?: Term[];
        "termsRangeConfig"?: any;
        "unitOfTime"?: string;
        "unitOfTimePlural"?: string;
    }
    interface PichinchaSpinner {
        "background"?: string;
        "border"?: number;
        "color"?: string;
        "size"?: number;
    }
    interface PichinchaSwitch {
        "checked"?: boolean;
        "disabled"?: boolean;
        "error"?: boolean;
        "idElement"?: string;
        "labelBefore"?: boolean;
        "offLabelClick"?: boolean;
        "onClickSwitch"?: (event: PichinchaSwitchCustomEvent<any>) => void;
        "value"?: string;
    }
    interface PichinchaTab {
        "active"?: boolean;
        "iconName"?: string;
        "name"?: string;
        "onTabActivate"?: (event: PichinchaTabCustomEvent<TabActivateEvent>) => void;
        "tabsStyle"?: 'default' | 'primary' | 'secondary' | 'default-gray';
    }
    interface PichinchaTabContent {
        "active"?: boolean;
        "name"?: string;
    }
    interface PichinchaTable {
        "actions"?: Actions[];
        "headers"?: Header[];
        "rows"?: Row[];
        "showRowStatus"?: boolean;
        "sizeStart"?: number;
    }
    interface PichinchaTabs {
        "activetab"?: string;
        "bkg"?: 'white' | 'gray';
        "tabsStyle"?: 'default' | 'primary' | 'secondary' | 'default-gray';
    }
    interface PichinchaTestimonial {
        "items"?: string;
    }
    interface PichinchaTooltip {
        "position"?: 'top' | 'bottom' | 'left' | 'right';
        "text"?: string;
        "textAlign"?: 'left' | 'center' | 'right';
    }
    interface PichinchaTypography {
        "align"?: 'inherit' | 'left' | 'center' | 'right' | 'justify';
        "category"?: 'heading' | 'paragraphs' | 'amounts' | 'actions';
        "color"?: AllColorType | Colors;
        /**
          * Deprecated
         */
        "inline_styles"?: object;
        "subCategory"?: | 'hero'
    | 'h1'
    | 'h2'
    | 'h3'
    | 'title'
    | 'subtitle'
    | 'body'
    | 'caption'
    | 'legal'
    | 'primary'
    | 'seconday'
    | 'buttons';
        /**
          * Deprecated
         */
        "variant"?: VariantText;
        /**
          * Deprecated
         */
        "weight"?: 'normal' | 'bold';
        "weightCategory"?: | 'book'
    | 'book-slab'
    | 'semi-bold'
    | 'bold'
    | 'semi-bold-slab'
    | 'underline'
    | 'medium'
    | 'small'
    | 'default';
        /**
          * Deprecated
         */
        "weight_color"?: | '100'
    | '200'
    | '300'
    | '400'
    | '500'
    | '600'
    | '700'
    | '800'
    | '900';
    }
    interface PichinchaTypographyWebview {
        "align"?: 'inherit' | 'left' | 'center' | 'right' | 'justify';
        "ariaHidden"?: any;
        "ariaLabel"?: any;
        "color"?: Colors;
        "inline_styles"?: object;
        "variant"?: VariantWebviewsText;
        "weight"?: 'book' | 'semiBold' | 'medium';
        "weight_color"?: | '100'
    | '200'
    | '300'
    | '400'
    | '500'
    | '600'
    | '700'
    | '800'
    | '900';
    }
    interface RadioButtomContainer {
        "checked"?: string;
        "nameRadio"?: string;
        "onSelectRadio"?: (event: RadioButtomContainerCustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "action-table": ActionTable;
        "badge-table": BadgeTable;
        "movil-email": MovilEmail;
        "pichincha-accordion": PichinchaAccordion;
        "pichincha-account-select-webview": PichinchaAccountSelectWebview;
        "pichincha-alert-message": PichinchaAlertMessage;
        "pichincha-avatar": PichinchaAvatar;
        "pichincha-brand": PichinchaBrand;
        "pichincha-button": PichinchaButton;
        "pichincha-callmeback": PichinchaCallmeback;
        "pichincha-carousel": PichinchaCarousel;
        "pichincha-carousel-item": PichinchaCarouselItem;
        "pichincha-check-box": PichinchaCheckBox;
        "pichincha-error-reload-webview": PichinchaErrorReloadWebview;
        "pichincha-feedback": PichinchaFeedback;
        "pichincha-feedback-webview": PichinchaFeedbackWebview;
        "pichincha-grid": PichinchaGrid;
        "pichincha-grid-v2": PichinchaGridV2;
        "pichincha-header-webview": PichinchaHeaderWebview;
        "pichincha-icon": PichinchaIcon;
        "pichincha-input": PichinchaInput;
        "pichincha-input-webview": PichinchaInputWebview;
        "pichincha-link": PichinchaLink;
        "pichincha-list": PichinchaList;
        "pichincha-message-bar": PichinchaMessageBar;
        "pichincha-modal": PichinchaModal;
        "pichincha-multiselect": PichinchaMultiselect;
        "pichincha-otp": PichinchaOtp;
        "pichincha-otp-input": PichinchaOtpInput;
        "pichincha-otp-timer": PichinchaOtpTimer;
        "pichincha-radio-buttom": PichinchaRadioButtom;
        "pichincha-review": PichinchaReview;
        "pichincha-select": PichinchaSelect;
        "pichincha-selector-box": PichinchaSelectorBox;
        "pichincha-spinner": PichinchaSpinner;
        "pichincha-switch": PichinchaSwitch;
        "pichincha-tab": PichinchaTab;
        "pichincha-tab-content": PichinchaTabContent;
        "pichincha-table": PichinchaTable;
        "pichincha-tabs": PichinchaTabs;
        "pichincha-testimonial": PichinchaTestimonial;
        "pichincha-tooltip": PichinchaTooltip;
        "pichincha-typography": PichinchaTypography;
        "pichincha-typography-webview": PichinchaTypographyWebview;
        "radio-buttom-container": RadioButtomContainer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "action-table": LocalJSX.ActionTable & JSXBase.HTMLAttributes<HTMLActionTableElement>;
            "badge-table": LocalJSX.BadgeTable & JSXBase.HTMLAttributes<HTMLBadgeTableElement>;
            "movil-email": LocalJSX.MovilEmail & JSXBase.HTMLAttributes<HTMLMovilEmailElement>;
            "pichincha-accordion": LocalJSX.PichinchaAccordion & JSXBase.HTMLAttributes<HTMLPichinchaAccordionElement>;
            "pichincha-account-select-webview": LocalJSX.PichinchaAccountSelectWebview & JSXBase.HTMLAttributes<HTMLPichinchaAccountSelectWebviewElement>;
            "pichincha-alert-message": LocalJSX.PichinchaAlertMessage & JSXBase.HTMLAttributes<HTMLPichinchaAlertMessageElement>;
            "pichincha-avatar": LocalJSX.PichinchaAvatar & JSXBase.HTMLAttributes<HTMLPichinchaAvatarElement>;
            "pichincha-brand": LocalJSX.PichinchaBrand & JSXBase.HTMLAttributes<HTMLPichinchaBrandElement>;
            "pichincha-button": LocalJSX.PichinchaButton & JSXBase.HTMLAttributes<HTMLPichinchaButtonElement>;
            "pichincha-callmeback": LocalJSX.PichinchaCallmeback & JSXBase.HTMLAttributes<HTMLPichinchaCallmebackElement>;
            "pichincha-carousel": LocalJSX.PichinchaCarousel & JSXBase.HTMLAttributes<HTMLPichinchaCarouselElement>;
            "pichincha-carousel-item": LocalJSX.PichinchaCarouselItem & JSXBase.HTMLAttributes<HTMLPichinchaCarouselItemElement>;
            "pichincha-check-box": LocalJSX.PichinchaCheckBox & JSXBase.HTMLAttributes<HTMLPichinchaCheckBoxElement>;
            "pichincha-error-reload-webview": LocalJSX.PichinchaErrorReloadWebview & JSXBase.HTMLAttributes<HTMLPichinchaErrorReloadWebviewElement>;
            "pichincha-feedback": LocalJSX.PichinchaFeedback & JSXBase.HTMLAttributes<HTMLPichinchaFeedbackElement>;
            "pichincha-feedback-webview": LocalJSX.PichinchaFeedbackWebview & JSXBase.HTMLAttributes<HTMLPichinchaFeedbackWebviewElement>;
            "pichincha-grid": LocalJSX.PichinchaGrid & JSXBase.HTMLAttributes<HTMLPichinchaGridElement>;
            "pichincha-grid-v2": LocalJSX.PichinchaGridV2 & JSXBase.HTMLAttributes<HTMLPichinchaGridV2Element>;
            "pichincha-header-webview": LocalJSX.PichinchaHeaderWebview & JSXBase.HTMLAttributes<HTMLPichinchaHeaderWebviewElement>;
            "pichincha-icon": LocalJSX.PichinchaIcon & JSXBase.HTMLAttributes<HTMLPichinchaIconElement>;
            "pichincha-input": LocalJSX.PichinchaInput & JSXBase.HTMLAttributes<HTMLPichinchaInputElement>;
            "pichincha-input-webview": LocalJSX.PichinchaInputWebview & JSXBase.HTMLAttributes<HTMLPichinchaInputWebviewElement>;
            "pichincha-link": LocalJSX.PichinchaLink & JSXBase.HTMLAttributes<HTMLPichinchaLinkElement>;
            "pichincha-list": LocalJSX.PichinchaList & JSXBase.HTMLAttributes<HTMLPichinchaListElement>;
            "pichincha-message-bar": LocalJSX.PichinchaMessageBar & JSXBase.HTMLAttributes<HTMLPichinchaMessageBarElement>;
            "pichincha-modal": LocalJSX.PichinchaModal & JSXBase.HTMLAttributes<HTMLPichinchaModalElement>;
            "pichincha-multiselect": LocalJSX.PichinchaMultiselect & JSXBase.HTMLAttributes<HTMLPichinchaMultiselectElement>;
            "pichincha-otp": LocalJSX.PichinchaOtp & JSXBase.HTMLAttributes<HTMLPichinchaOtpElement>;
            "pichincha-otp-input": LocalJSX.PichinchaOtpInput & JSXBase.HTMLAttributes<HTMLPichinchaOtpInputElement>;
            "pichincha-otp-timer": LocalJSX.PichinchaOtpTimer & JSXBase.HTMLAttributes<HTMLPichinchaOtpTimerElement>;
            "pichincha-radio-buttom": LocalJSX.PichinchaRadioButtom & JSXBase.HTMLAttributes<HTMLPichinchaRadioButtomElement>;
            "pichincha-review": LocalJSX.PichinchaReview & JSXBase.HTMLAttributes<HTMLPichinchaReviewElement>;
            "pichincha-select": LocalJSX.PichinchaSelect & JSXBase.HTMLAttributes<HTMLPichinchaSelectElement>;
            "pichincha-selector-box": LocalJSX.PichinchaSelectorBox & JSXBase.HTMLAttributes<HTMLPichinchaSelectorBoxElement>;
            "pichincha-spinner": LocalJSX.PichinchaSpinner & JSXBase.HTMLAttributes<HTMLPichinchaSpinnerElement>;
            "pichincha-switch": LocalJSX.PichinchaSwitch & JSXBase.HTMLAttributes<HTMLPichinchaSwitchElement>;
            "pichincha-tab": LocalJSX.PichinchaTab & JSXBase.HTMLAttributes<HTMLPichinchaTabElement>;
            "pichincha-tab-content": LocalJSX.PichinchaTabContent & JSXBase.HTMLAttributes<HTMLPichinchaTabContentElement>;
            "pichincha-table": LocalJSX.PichinchaTable & JSXBase.HTMLAttributes<HTMLPichinchaTableElement>;
            "pichincha-tabs": LocalJSX.PichinchaTabs & JSXBase.HTMLAttributes<HTMLPichinchaTabsElement>;
            "pichincha-testimonial": LocalJSX.PichinchaTestimonial & JSXBase.HTMLAttributes<HTMLPichinchaTestimonialElement>;
            "pichincha-tooltip": LocalJSX.PichinchaTooltip & JSXBase.HTMLAttributes<HTMLPichinchaTooltipElement>;
            "pichincha-typography": LocalJSX.PichinchaTypography & JSXBase.HTMLAttributes<HTMLPichinchaTypographyElement>;
            "pichincha-typography-webview": LocalJSX.PichinchaTypographyWebview & JSXBase.HTMLAttributes<HTMLPichinchaTypographyWebviewElement>;
            "radio-buttom-container": LocalJSX.RadioButtomContainer & JSXBase.HTMLAttributes<HTMLRadioButtomContainerElement>;
        }
    }
}
