import { ComponentInterface, EventEmitter } from '../../../stencil-public-runtime';
import { HTMLStencilElement } from '../../../stencil-public-runtime';
import { Colors } from '../../../global/interfaces';
export declare class Input implements ComponentInterface {
  idElement: string;
  nameElement: string;
  type: string;
  hidePasswordText: string;
  showPasswordText: string;
  showPasswordToggle: boolean;
  label: string;
  placeholder: string;
  normalHelper: string;
  errorHelper: string;
  value: string;
  state: 'normal' | 'disabled' | 'success' | 'error';
  size: 'extra-small' | 'small' | 'medium' | 'large';
  fullWidth: boolean;
  maxLength: number;
  filterRegex: string;
  tabIndexElement: number;
  showMaxLength: boolean;
  showIconStatus: boolean;
  controlEvent: boolean;
  autofocus: boolean;
  floatingLabel: boolean;
  private isFilled;
  tooltip: string;
  tooltipBody: any;
  private hasTooltipBodySlot;
  showTooltipOnChange: boolean;
  hideNumberHandles: boolean;
  autoComplete: boolean;
  class: string;
  inputmode: string;
  pattern: string;
  inlineStyles: {
    [key: string]: string;
  };
  ifocus: EventEmitter;
  ikeydown: EventEmitter;
  ikeypress: EventEmitter;
  ichange: EventEmitter;
  ikeyup: EventEmitter;
  iblur: EventEmitter;
  iPaste: EventEmitter;
  passwordToggleMouseDown: EventEmitter;
  passwordToggleMouseUp: EventEmitter;
  passwordToggleMouseLeave: EventEmitter;
  passwordToggleTouchEnd: EventEmitter;
  passwordToggleTouchCancel: EventEmitter;
  eventValue: EventEmitter;
  showInputAsText: boolean;
  showTooltipManually: boolean;
  isActive: boolean;
  valueTemp: any;
  caretTemp: any;
  hostElement: HTMLStencilElement;
  componentWillLoad(): void;
  handleEvent(e: any, emitter: EventEmitter): void;
  private onHidePasswordBtn;
  private onUncontrolledChangeEvent;
  private isEmpty;
  private onControlledChangeEvent;
  private onBlurEvent;
  private onKeyPressEvent;
  private handleFilterRegex;
  private shouldRenderHidePasswordBtn;
  get inputType(): string;
  get labelColor(): Colors;
  private onIsFLoatingLabel;
  private renderStatusIcon;
  render(): any;
}
