export const flowValues = Object.freeze({
  shared: {
    productCode: 'TU_BAN_PRO',
    accountHashSelected:
      '42e976aea883be9ad3b29487ab3d1a64778bdbfbac9d02f30941d30600b76585',
    planSelected: 'TU_BAN_PRO_2',
    periodicitySelected: 'MONTHLY',
    transactionReference: '60547864-a16d-4571-9771-25d0f98ffc11',
    key: 'aUYg77Dfr/mA8NhDEHfVRbksKZjbdPnuV3ARE29k3vCL2/dnEgSBJl1xbo/Dey3t5LXDvGIRgV7QUAvEacJSHKqyrns3ej5fFPxl59bAxPBTM4cONP2NyRJKomx9RmLA9QOv9x4=',
    contentLoaded: true,
    step: 'GENERAL_ERROR',
    status: 'WAIT_LOAD',
  },
})

export const globalValues = Object.freeze({
  security: {
    authEvent: {
      clientId: '0702446154',
      clientIdType: '0001',
      device: 'hvOi3g0+VYx0HWfSLHp+iVSbRGJVgV6eWs56ElRyctrx',
      guid: '8d4d1a40590144be9046cf26f9a468d6',
      session: '9b8cb2a8-757d-46a6-a891-ccee5a032090',
      ip: '0.0.0.0',
      jwtToken:
        'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzdWJqZWN0LXN1YmplY3QiLCJhdWQiOlsiYXVkaWVuY2UxIiwiYXVkaWVuY2UyIl0sImlzcyI6InVybjpcL1wvYXBpZ2VlLWVkZ2UtSldULXBvbGljeS10ZXN0IiwiZXhwIjoxNjkyMzMwNzE5LCJpYXQiOjE2OTIzMzAxMTksImp0aSI6IjYyZDc1ZGRiLTIyZDMtNGFmOS05NWEyLTE3NDAyZDlhNjJjYiJ9.17fqp3Dxc-lvJ--m_axZz2t-RBfEqVpIOvwRDkYCc5c',
      cif: '2383122',
      os: 'android',
      channel: 'movil',
    },
    isAuthenticated: true,
  },
  error: [
    {
      code: '500',
      title: 'Estamos realizando mejoras en nuestro servicio en este momento.',
      message: 'Por favor, vuelve a intentarlo más tarde.',
      details: {},
    },
  ],
  portalHub: {
    code: 'POR_BP_EMB_PROD',
    isActive: true,
    content: {
      home: {
        sectionHero: {
          isActive: true,
          key: 'sectionHero',
          order: 0,
          title: {
            isActive: true,
            key: 'title',
            order: 0,
            value: 'Pablo, vive tranquilo, nosotros cuidamos de ti.',
            aria: 'Pablo, vive tranquilo, nosotros cuidamos de ti.',
          },
        },
        sectionProducts: {
          isActive: true,
          key: 'sectionProducts',
          order: 1,
          cards: {
            TU_BAN_PRO: {
              isActive: true,
              key: 'TU_BAN_PRO',
              order: 0,
              title: {
                isActive: true,
                key: 'title',
                order: 0,
                value: 'Seguro por Robos y Fraudes',
                aria: 'Pablo, vive tranquilo, nosotros cuidamos de ti.',
              },
              description: {
                isActive: true,
                key: 'description',
                order: 1,
                value:
                  'Suma una <strong>capa extra</strong> de protección para\r\n  tus cuentas y tarjetas.',
                aria: 'Suma una capa extra de protección para tus cuentas y tarjetas.',
              },
              paymentType: {
                isActive: true,
                key: 'paymentType',
                order: 2,
                value: 'Precio mensual',
                aria: 'Precio mensual',
              },
              price: {
                isActive: true,
                key: 'price',
                order: 3,
                value: '$4,09',
                aria: '$4,09',
              },
              coverages: {
                isActive: true,
                key: 'coverages',
                order: 4,
                items: [
                  {
                    isActive: true,
                    key: 'COBE176',
                    order: 1,
                    coverageCode: 'COBE176',
                    description: {
                      isActive: true,
                      key: 'description',
                      order: 1,
                      value:
                        '<strong>Hasta $10.000 al año por </strong><br>cargos fraudulentos en tus cuentas',
                      aria: 'Hsta $10.000 al año por cargos raudulentos en tus cuentas',
                    },
                  },
                  {
                    isActive: true,
                    key: 'COBE177',
                    order: 2,
                    coverageCode: 'COBE177',
                    description: {
                      isActive: true,
                      key: 'description',
                      order: 1,
                      value:
                        '<strong>Hasta $1.400 al año por </strong><br>robos en cajeros o ventanillas',
                      aria: 'Hasta $10.000 al año por robos en cajeros o ventanillas',
                    },
                  },
                  {
                    isActive: true,
                    key: 'COBE178',
                    order: 3,
                    coverageCode: 'COBE178',
                    description: {
                      isActive: true,
                      key: 'description',
                      order: 1,
                      value:
                        '<strong>Protección desde el primer día,  </strong><br>garantizando el respaldo necesario',
                      aria: 'sta $10.000 al año por cargos fraudulentos en tus cuentas',
                    },
                  },
                ],
                title: {
                  isActive: true,
                  key: 'title',
                  order: 0,
                  value: '<strong>Este seguro cubre:</strong>',
                  aria: 'Este seguro cubre:',
                },
              },
              action: {
                isActive: true,
                key: 'action',
                order: 5,
                urlTarget: 'PRODUCT_DETAIL',
                aria: 'Descubre qué incluye tu seguro',
                value: 'Descubre qué incluye tu seguro',
              },
            },
            LIFE_HEALTH: {
              isActive: true,
              key: 'LIFE_HEALTH',
              order: 1,
              title: {
                isActive: true,
                key: 'title',
                order: 0,
                value: 'Seguro por Robos y Fraudes',
                aria: 'Pablo, vive tranquilo, nosotros cuidamos de ti.',
              },
              description: {
                isActive: true,
                key: 'description',
                order: 1,
                value:
                  'Suma una <strong>capa extra</strong> de protección para\r\n  tus cuentas y tarjetas.',
                aria: 'Suma una capa extra de protección para tus cuentas y tarjetas.',
              },
              paymentType: {
                isActive: true,
                key: 'paymentType',
                order: 2,
                value: 'Precio mensual',
                aria: 'Precio mensual',
              },
              price: {
                isActive: true,
                key: 'price',
                order: 3,
                value: '$4,09',
                aria: '$4,09',
              },
              coverages: {
                isActive: true,
                key: 'coverages',
                order: 4,
                items: [
                  {
                    isActive: true,
                    key: 'COBE176',
                    order: 1,
                    description: {
                      isActive: true,
                      key: 'description',
                      order: 1,
                      value:
                        '<strong>Hasta $10.000 al año por </strong><br>cargos fraudulentos en tus cuentas',
                      aria: 'Hsta $10.000 al año por cargos raudulentos en tus cuentas',
                    },
                  },
                  {
                    isActive: true,
                    key: 'COBE177',
                    order: 2,
                    description: {
                      isActive: true,
                      key: 'description',
                      order: 1,
                      value:
                        '<strong>Hasta $1.400 al año por </strong><br>robos en cajeros o ventanillas',
                      aria: 'Hasta $10.000 al año por robos en cajeros o ventanillas',
                    },
                  },
                  {
                    isActive: true,
                    key: 'COBE178',
                    order: 3,
                    description: {
                      isActive: true,
                      key: 'description',
                      order: 1,
                      value:
                        '<strong>Protección desde el primer día,  </strong><br>garantizando el respaldo necesario',
                      aria: 'sta $10.000 al año por cargos fraudulentos en tus cuentas',
                    },
                  },
                ],
                title: {
                  isActive: true,
                  key: 'title',
                  order: 0,
                  value: '<strong>Este seguro cubre:</strong>',
                  aria: 'Este seguro cubre:',
                },
              },
              action: {
                isActive: true,
                key: 'action',
                order: 5,
                urlTarget: 'PRODUCT_DETAIL',
                aria: 'Descubre qué incluye tu seguro',
                value: 'Descubre qué incluye tu seguro',
              },
            },
          },
        },
      },
    },
    params: {},
  },
})

export const appValues = Object.freeze({
  products: {
    LIFE_HEALTH: {
      code: 'LIFE_HEALTH',
      name: 'Vida y Salud Protegida',
      sale: null,
      coverages: {
        LH_COBE001: {
          id: 'bd05d76a-a634-4e2c-b328-08dcc21c85f2',
          name: 'Muerte por cualquier causa',
          isActive: true,
          limitValueMin: 0,
          limitValueMax: 0,
          limitEventMin: 0,
          limitEventMax: 0,
        },
        LH_COBE002: {
          id: '309a6e80-28ce-4077-b329-08dcc21c85f2',
          name: 'Incluye 4 consultas de medicina general anuales y los medicamentos que te receten',
          isActive: true,
          limitValueMin: 0,
          limitValueMax: 0,
          limitEventMin: 0,
          limitEventMax: 0,
        },
        LH_COBE003: {
          id: 'a1697668-e424-4922-b32a-08dcc21c85f2',
          name: 'Incluye 3 consultas de medicina en 8 especialidades al año y los medicamentos recetados',
          isActive: true,
          limitValueMin: 0,
          limitValueMax: 0,
          limitEventMin: 0,
          limitEventMax: 0,
        },
        LH_COBE004: {
          id: 'd3384114-cd12-4995-b32b-08dcc21c85f2',
          name: 'Bono de $100 para exámenes de laboratorio y rayos X solicitados en las consultas médicas',
          isActive: true,
          limitValueMin: 0,
          limitValueMax: 0,
          limitEventMin: 0,
          limitEventMax: 0,
        },
        LH_COBE005: {
          id: '68500071-4b85-466b-b32c-08dcc21c85f2',
          name: 'Consultas de telemedicina ilimitada',
          isActive: true,
          limitValueMin: 0,
          limitValueMax: 0,
          limitEventMin: 0,
          limitEventMax: 0,
        },
      },
      benefits: {},
      assistances: {},
      exclusions: {},
      insuranceName: 'Seguros del Pichincha',
      plans: {
        LIFE_HEALTH_2: {
          name: 'Recomendado',
          coverages: {
            LH_COBE005: {
              name: 'Consultas de telemedicina ilimitada',
              isActive: true,
              limitValueMin: 0,
              limitValueMax: 0,
              limitEventMin: 0,
              limitEventMax: 0,
              coverageLimit: {
                minAmount: '0.00',
                maxAmount: '0.00',
                minEvents: 0,
                maxEvents: 0,
              },
            },
            LH_COBE004: {
              name: 'Bono de $100 para exámenes de laboratorio y rayos X solicitados en las consultas médicas',
              isActive: true,
              limitValueMin: 0,
              limitValueMax: 0,
              limitEventMin: 0,
              limitEventMax: 0,
              coverageLimit: {
                minAmount: '0.00',
                maxAmount: '0.00',
                minEvents: 0,
                maxEvents: 0,
              },
            },
            LH_COBE003: {
              name: 'Incluye 3 consultas de medicina en 8 especialidades al año y los medicamentos recetados',
              isActive: true,
              limitValueMin: 0,
              limitValueMax: 0,
              limitEventMin: 0,
              limitEventMax: 0,
              coverageLimit: {
                minAmount: '0.00',
                maxAmount: '0.00',
                minEvents: 0,
                maxEvents: 3,
              },
            },
            LH_COBE002: {
              name: 'Incluye 4 consultas de medicina general anuales y los medicamentos que te receten',
              isActive: true,
              limitValueMin: 0,
              limitValueMax: 0,
              limitEventMin: 0,
              limitEventMax: 0,
              coverageLimit: {
                minAmount: '0.00',
                maxAmount: '0.00',
                minEvents: 0,
                maxEvents: 4,
              },
            },
            LH_COBE001: {
              name: 'Muerte por cualquier causa',
              isActive: true,
              limitValueMin: 0,
              limitValueMax: 0,
              limitEventMin: 0,
              limitEventMax: 0,
              coverageLimit: {
                minAmount: '0.00',
                maxAmount: '25000.00',
                minEvents: 0,
                maxEvents: 0,
              },
            },
          },
          periodicityOptions: {
            ANNUAL: {
              description: 'Pago anual',
              factor: 12,
              name: 'Anual',
              order: 2,
              price: '168.70',
              totalPrice: '175.89',
              taxes: '7.19',
            },
            MONTHLY: {
              description: 'Pago mensual',
              factor: 1,
              name: 'Mensual',
              order: 1,
              price: '15.33',
              totalPrice: '15.99',
              taxes: '0.66',
            },
          },
          paymentMethodOptions: {
            BANK_ACCOUNT: {
              description: 'Cuenta bancaria',
              name: 'Cuenta',
              order: 1,
            },
            CREDIT_CARD: {
              description: 'Tarjeta de crédito',
              name: 'Tarjeta de crédito',
              order: 2,
            },
          },
        },
        LIFE_HEALTH_3: {
          name: 'Preferido',
          coverages: {
            LH_COBE001: {
              name: 'Muerte por cualquier causa',
              isActive: true,
              limitValueMin: 0,
              limitValueMax: 0,
              limitEventMin: 0,
              limitEventMax: 0,
              coverageLimit: {
                minAmount: '0.00',
                maxAmount: '40000.00',
                minEvents: 0,
                maxEvents: 0,
              },
            },
            LH_COBE002: {
              name: 'Incluye 4 consultas de medicina general anuales y los medicamentos que te receten',
              isActive: true,
              limitValueMin: 0,
              limitValueMax: 0,
              limitEventMin: 0,
              limitEventMax: 0,
              coverageLimit: {
                minAmount: '0.00',
                maxAmount: '0.00',
                minEvents: 0,
                maxEvents: 4,
              },
            },
            LH_COBE003: {
              name: 'Incluye 3 consultas de medicina en 8 especialidades al año y los medicamentos recetados',
              isActive: true,
              limitValueMin: 0,
              limitValueMax: 0,
              limitEventMin: 0,
              limitEventMax: 0,
              coverageLimit: {
                minAmount: '0.00',
                maxAmount: '0.00',
                minEvents: 0,
                maxEvents: 3,
              },
            },
            LH_COBE004: {
              name: 'Bono de $100 para exámenes de laboratorio y rayos X solicitados en las consultas médicas',
              isActive: true,
              limitValueMin: 0,
              limitValueMax: 0,
              limitEventMin: 0,
              limitEventMax: 0,
              coverageLimit: {
                minAmount: '0.00',
                maxAmount: '100.00',
                minEvents: 0,
                maxEvents: 1,
              },
            },
            LH_COBE005: {
              name: 'Consultas de telemedicina ilimitada',
              isActive: true,
              limitValueMin: 0,
              limitValueMax: 0,
              limitEventMin: 0,
              limitEventMax: 0,
              coverageLimit: {
                minAmount: '0.00',
                maxAmount: '0.00',
                minEvents: 0,
                maxEvents: 0,
              },
            },
          },
          periodicityOptions: {
            ANNUAL: {
              description: 'Pago anual',
              factor: 12,
              name: 'Anual',
              order: 2,
              price: '263.88',
              totalPrice: '274.89',
              taxes: '11.01',
            },
            MONTHLY: {
              description: 'Pago mensual',
              factor: 1,
              name: 'Mensual',
              order: 1,
              price: '23.99',
              totalPrice: '24.99',
              taxes: '1.00',
            },
          },
          paymentMethodOptions: {
            BANK_ACCOUNT: {
              description: 'Cuenta bancaria',
              name: 'Cuenta',
              order: 1,
            },
            CREDIT_CARD: {
              description: 'Tarjeta de crédito',
              name: 'Tarjeta de crédito',
              order: 2,
            },
          },
        },
        LIFE_HEALTH_1: {
          name: 'Económico',
          coverages: {
            LH_COBE001: {
              name: 'Muerte por cualquier causa',
              isActive: true,
              limitValueMin: 0,
              limitValueMax: 0,
              limitEventMin: 0,
              limitEventMax: 0,
              coverageLimit: {
                minAmount: '0.00',
                maxAmount: '15000.00',
                minEvents: 0,
                maxEvents: 0,
              },
            },
            LH_COBE002: {
              name: 'Incluye 4 consultas de medicina general anuales y los medicamentos que te receten',
              isActive: true,
              limitValueMin: 0,
              limitValueMax: 0,
              limitEventMin: 0,
              limitEventMax: 0,
              coverageLimit: {
                minAmount: '0.00',
                maxAmount: '0.00',
                minEvents: 0,
                maxEvents: 4,
              },
            },
            LH_COBE003: {
              name: 'Incluye 3 consultas de medicina en 8 especialidades al año y los medicamentos recetados',
              isActive: true,
              limitValueMin: 0,
              limitValueMax: 0,
              limitEventMin: 0,
              limitEventMax: 0,
              coverageLimit: {
                minAmount: '0.00',
                maxAmount: '0.00',
                minEvents: 0,
                maxEvents: 0,
              },
            },
            LH_COBE004: {
              name: 'Bono de $100 para exámenes de laboratorio y rayos X solicitados en las consultas médicas',
              isActive: true,
              limitValueMin: 0,
              limitValueMax: 0,
              limitEventMin: 0,
              limitEventMax: 0,
              coverageLimit: {
                minAmount: '0.00',
                maxAmount: '0.00',
                minEvents: 0,
                maxEvents: 0,
              },
            },
            LH_COBE005: {
              name: 'Consultas de telemedicina ilimitada',
              isActive: true,
              limitValueMin: 0,
              limitValueMax: 0,
              limitEventMin: 0,
              limitEventMax: 0,
              coverageLimit: {
                minAmount: '0.00',
                maxAmount: '0.00',
                minEvents: 0,
                maxEvents: 0,
              },
            },
          },
          periodicityOptions: {
            ANNUAL: {
              description: 'Pago anual',
              factor: 12,
              name: 'Anual',
              order: 2,
              price: '105.23',
              totalPrice: '109.89',
              taxes: '4.66',
            },
            MONTHLY: {
              description: 'Pago mensual',
              factor: 1,
              name: 'Mensual',
              order: 1,
              price: '9.57',
              totalPrice: '9.99',
              taxes: '0.42',
            },
          },
          paymentMethodOptions: {
            BANK_ACCOUNT: {
              description: 'Cuenta bancaria',
              name: 'Cuenta',
              order: 1,
            },
            CREDIT_CARD: {
              description: 'Tarjeta de crédito',
              name: 'Tarjeta de crédito',
              order: 2,
            },
          },
        },
      },
      portal: {
        code: 'POR_BP_WV_LH',
        isActive: true,
        content: {
          sale: {
            toolbar: 'Default value',
            faq: {
              isActive: true,
              key: 'faq',
              order: 5,
              questions: [
                {
                  isActive: true,
                  key: 'question_2',
                  order: 1,
                  title: '¿Cómo cancelo?',
                  track: 'BM_Segu_Frau_05Posventa_Btn_Clk_Accd2',
                  answer:
                    'Puedes cancelar tu seguro sin recargos, cuando quieras, llamando al (02) 2999 999.',
                },
                {
                  isActive: true,
                  key: 'question_3',
                  order: 2,
                  title: '¿Quién respalda este producto?',
                  track: 'BM_Segu_Frau_05Posventa_Btn_Clk_Accd3',
                  answer:
                    'Es un producto de AIG Metropolitana de seguros con el asesoramiento y gestión de Novaecuador S.A.',
                },
                {
                  isActive: true,
                  key: 'question_1',
                  order: 0,
                  track: 'BM_Segu_Frau_05Posventa_Btn_Clk_Accd1',
                  answer:
                    'Reporta tu caso lo más pronto posible llamando al (02) 299 9999, ellos te guiarán en el proceso hasta la recuperación de tu dinero.',
                  title: '¿Cómo usar el seguro?',
                },
              ],
              title: {
                isActive: true,
                key: 'title',
                order: 0,
                value: 'Preguntas frecuentes',
                aria: 'Preguntas frecuentes, sección con tres opciones desplegables.',
              },
            },
            actions: {
              cta: {
                isActive: true,
                key: 'cta',
                order: 2,
                aria: 'Cómo usar tu seguro',
                value: 'Cómo usar tu seguro',
              },
              whatsapp: {
                isActive: true,
                key: 'whatsapp',
                order: 1,
                aria: 'Escríbenos al WhatsApp',
                value:
                  'https://api.whatsapp.com/send?phone=593995546002&text=Hola,%20vengo%20de%20mi%20Banca%20M%C3%B3vil%20de%20Banco%20Pichincha%20y%20necesito%20informaci%C3%B3n%20sobre%20mi%20seguro%20por%20robos%20y%20fraudes.',
              },
              call: {
                isActive: true,
                key: 'call',
                order: 0,
                value: 'tel:029999999',
                aria: 'Llámanos 24 horas 7 días a la semana',
              },
              userGuide: {
                isActive: true,
                key: 'userGuide',
                order: 0,
                value: 'guia-de-uso-frauds',
                aria: 'Descargar certificado',
              },
            },
            description: {
              isActive: true,
              key: 'description',
              order: 2,
              value: 'Plan Cobertura Total | {0}',
              aria: 'Plan Cobertura Total, por {0}',
            },
            range: {
              isActive: true,
              key: 'range',
              order: 3,
              aria: 'Tu fecha de contratación fue: {0}, los débitos se realizan todos los {1}',
              items: [
                {
                  isActive: true,
                  key: 'range_1',
                  order: 0,
                  value: '{0}',
                  label: 'Fecha de contratación',
                },
                {
                  isActive: true,
                  key: 'range_2',
                  order: 1,
                  label: 'Fecha débito',
                  value: '{1}',
                },
              ],
            },
            coverages: {
              isActive: true,
              key: 'coverages',
              order: 4,
              headers: {
                isActive: true,
                key: 'headers',
                order: 1,
                label: 'Casos',
                value: 'Máximo anual',
              },
              items: [
                {
                  isActive: true,
                  key: 'COBE002',
                  order: 1,
                  aria: 'Robos en cajeros o ventanillas, 1400 dólares',
                  label: 'Robos en cajeros o ventanillas',
                  value: '$ 1.400',
                },
                {
                  isActive: true,
                  key: 'COBE004',
                  order: 3,
                  label: 'Robos de billetera o bolso',
                  aria: 'Robos de billetera o bolso,  600 dólares',
                  value: '$ 600',
                },
                {
                  isActive: true,
                  key: 'COBE001',
                  order: 0,
                  label: 'Cargos fraudulentos',
                  value: '$ 10.000',
                  aria: 'Cargos fraudulentos, 10000 dólares.',
                },
                {
                  isActive: true,
                  key: 'COBE005',
                  order: 4,
                  label: 'Primeros auxilios por robo en cajero',
                  aria: 'Primeros auxilios por robo en cajero, 200 dólares',
                  value: '$ 200',
                },
                {
                  isActive: true,
                  key: 'COBE003',
                  order: 2,
                  label: 'Compras con tus tarjetas',
                  value: '$ 1.000',
                  aria: 'Compras con tus tarjetas,  1000 dólares',
                },
              ],
              description: {
                isActive: true,
                key: 'description',
                order: 0,
                aria: 'Recuerda que puedes usar 2 veces cada caso hasta cubrir el máximo anual',
                value:
                  'Recuerda que puedes usar 2 veces cada caso hasta cubrir el máximo anual',
              },
            },
            title: 'Seguro por robos y fraudes',
            insuranceCarrier: {
              isActive: true,
              key: 'insuranceCarrier',
              order: 3,
              value: 'AIG Metropolitana',
              aria: 'Un producto de: AIG Metropolitana',
              label: 'Un producto de:',
            },
            contract: {
              isActive: true,
              key: 'contract',
              order: 1,
              aria: 'Número de contrato:  {0}',
              value: 'Nro. contrato:  {0}',
            },
          },
          acceptance: {
            title: 'Confirma los datos para la contratación',
            toolbar: {
              isActive: true,
              key: 'toolbar',
              order: 3,
              title: {
                isActive: true,
                key: 'title',
                order: 0,
                aria: 'Seguro por robos y fraudes',
                value: 'Seguro por robos y fraudes',
              },
            },
            actions: {
              isActive: true,
              key: 'actions',
              order: 8,
              cta: {
                isActive: true,
                key: 'cta',
                order: 7,
                value: 'Confirmar',
                aria: 'Confirmar contratación',
              },
              btnCancel: {
                isActive: true,
                key: 'btnCancel',
                order: 0,
                value: 'Cancelar',
                aria: 'Cancelar y vuelve al inicio',
              },
            },
            descriptions: {
              isActive: true,
              key: 'descriptions',
              order: 1,
              toCompany: 'A la empresa:',
              companyName: 'Novaecuador S.A.',
              policy: 'Póliza maestra nro.: 50157',
              aria: 'Vas a pagar {1}. De la cuenta: {0}. A la empresa: Novaecuador S.A. Por el producto: Seguro por robos y fraudes. Cobertura total. Póliza maestra número: 5 0 1 5 7',
              productName: 'Seguro por robos y fraudes. Cobertura Total',
              forProduct: 'Por el producto:',
              toPay: 'Vas a pagar {1}: {0} inc. impuestos',
              from: 'De la cuenta: {0}',
            },
          },
          success: {
            moreInformation: {
              isActive: true,
              key: 'moreInformation',
              order: 4,
              description: {
                isActive: true,
                key: 'description',
                order: 0,
                value: 'Para requerimientos o más información',
                aria: 'Si tienes requerimientos o más información, comunícate a Banca telefónica.',
              },
              action: {
                isActive: true,
                key: 'action',
                order: 0,
                aria: 'Llamar (02) 2999 999',
                link: 'tel:022999999',
                label: 'Llámanos al (02)2999 999',
              },
            },
            alert: {
              isActive: true,
              key: 'alert',
              order: 2,
              aria: 'Enviamos a tu correo el certificado del seguro',
              value: 'Enviamos a tu correo el certificado',
            },
            description: 'Póliza maestra nro.: 50157',
            details: [
              {
                isActive: true,
                key: 'item_2',
                order: 1,
                subItems: [
                  {
                    isActive: true,
                    key: 'subItem_2',
                    order: 1,
                    value: '{1} de cada mes',
                    label: 'Fecha para débitos',
                  },
                  {
                    isActive: true,
                    key: 'subItem_1',
                    order: 0,
                    value: '{0}',
                    label: 'Cuenta de débito',
                  },
                ],
                aria: 'Cuenta de débito termina en {4}, fecha para débitos {1}',
              },
              {
                isActive: true,
                key: 'item_3',
                order: 2,
                aria: 'Fecha de vencimiento Indefinido, fecha de contratación {3}',
                subItems: [
                  {
                    isActive: true,
                    key: 'subItem_1',
                    order: 0,
                    label: 'Fecha de vencimiento',
                    value: 'Indefinido',
                  },
                  {
                    isActive: true,
                    key: 'subItem_2',
                    order: 1,
                    label: 'Fecha de contratación',
                    value: '{2}',
                  },
                ],
              },
              {
                isActive: true,
                key: 'item_1',
                order: 0,
                subItems: [
                  {
                    isActive: true,
                    key: 'subitem_2',
                    order: 1,
                    label: 'Seguro por robos y fraudes',
                    value: 'Cobertura Total',
                  },
                  {
                    isActive: true,
                    key: 'subItem_1',
                    order: 0,
                    value: '{5}',
                    label: 'Precio incluido impuestos',
                  },
                ],
                aria: 'Seguro por robos y fraudes, cobertura total. Precio incluido impuesto',
              },
            ],
            title: {
              isActive: true,
              key: 'title',
              order: 0,
              value: '¡Contratación exitosa!',
              aria: 'Tu contratacion fue exitosa',
            },
            toolbar: {
              isActive: true,
              key: 'toolbar',
              order: 4,
              title: {
                isActive: true,
                key: 'title',
                order: 0,
                aria: 'Banco Pichincha',
                value: 'Banco Pichincha',
              },
            },
            actions: {
              isActive: true,
              key: 'actions',
              order: 9,
              btnDownload: {
                isActive: true,
                key: 'btnDownload',
                order: 1,
                value: 'Cómo usar tu seguro',
                aria: 'Descargar guía de uso del Seguro',
              },
              cta: {
                isActive: true,
                key: 'cta',
                order: 0,
                aria: 'Finalizar',
                value: 'Finalizar',
              },
            },
          },
          multiOffer: {
            offer: {
              isActive: true,
              key: 'offer',
              order: 7,
              title: 'Seguro por robo y fraude',
              description: '$2,77 /mes',
            },
            previous: {
              isActive: true,
              key: 'previous',
              order: 8,
              title: 'Seguro por robos y fraudes',
              description: 'Protección por cargos fraudulentos',
            },
          },
          selectAccount: {
            title: {
              isActive: true,
              key: 'title',
              order: 0,
              aria: 'Selecciona entre tus cuentas',
              value: 'Mis cuentas',
            },
            toolbar: {
              isActive: true,
              key: 'toolbar',
              order: 2,
              title: {
                isActive: true,
                key: 'title',
                order: 0,
                aria: 'Elige tu cuenta',
                value: 'Elige tu cuenta',
              },
            },
          },
          productInfo: {
            alert: {
              isActive: true,
              key: 'alert',
              order: 3,
              aria: 'Puedes cancelar en cualquier momento.',
              description: 'Puedes cancelar en cualquier momento.',
            },
            toolbar: {
              isActive: true,
              key: 'toolbar',
              order: 1,
              title: {
                isActive: true,
                key: 'title',
                order: 0,
                value: 'Seguro por robos y fraudes',
                aria: 'Seguro por robos y fraudes',
              },
            },
            information: 'El valor a pagar incluye impuestos',
            select: {
              isActive: true,
              key: 'select',
              order: 4,
              multipleAccount: 'Cuenta a debitar el seguro',
              singleAccount: 'Cuenta a debitar el seguro',
            },
            actions: {
              isActive: true,
              key: 'actions',
              order: 10,
              cta: {
                isActive: true,
                key: 'cta',
                order: 6,
                aria: {
                  isActive: true,
                  key: 'aria',
                  order: 1,
                  enabled: 'Aceptar',
                  disabled:
                    'Para continuar marca la casilla de autorización anterior. Aceptar botón desactivado',
                },
                value: 'Aceptar',
              },
            },
            title: 'Plan Cobertura Total',
            description: {
              isActive: true,
              key: 'description',
              order: 2,
              aria: 'Un producto de AIG Metropolitana',
              value: 'Un producto de AIG Metropolitana',
            },
            disclaimer: {
              isActive: true,
              key: 'disclaimer',
              order: 5,
              description:
                'Autorizo el débito recurrente y a compartir el medio de pago con el prestador del servicio y Novaecuador S.A. para contratar el seguro por robos y fraudes ',
              action: 'Cobertura Total.',
            },
          },
          productDetail: {
            title: {
              isActive: true,
              key: 'title',
              order: 1,
              aria: 'Un seguro que protege tu dinero por 4 dólares con 9 centavos al mes',
              value: 'Un seguro que protege tu dinero por $4,09 al mes',
            },
            alert: {
              isActive: true,
              key: 'alert',
              order: 3,
              action: {
                isActive: true,
                key: 'action',
                order: 1,
                value: 'Conoce más del seguro por robos y fraudes',
                aria: 'Descargar guía de uso del seguro por robos y fraudes',
              },
              description:
                'Puedes ser cubierto hasta 2 veces al año o hasta cubrir el valor máximo anual por caso.',
            },
            description: {
              isActive: true,
              key: 'description',
              order: 1,
              value: 'Mantén tus cuentas y tarjetas de crédito protegidas ¡siempre!',
              aria: 'Con un pago mensual de 4 dólares con 9 centavos recupera tu dinero perdido en los siguientes casos, lista con 6 beneficios:',
            },
            faq: {
              isActive: true,
              key: 'faq',
              order: 4,
              questions: [
                {
                  isActive: true,
                  key: 'question_3',
                  order: 2,
                  title: '¿Quién respalda este producto?',
                  track: 'BM_Segu_Frau_01Onbor_Btn_Clk_Accd3',
                  answer:
                    'Es un producto de AIG Metropolitana de seguros con el asesoramiento y gestión de Novaecuador S.A.',
                },
                {
                  isActive: true,
                  key: 'question_2',
                  order: 1,
                  title: '¿Cómo cancelo?',
                  answer:
                    'Puedes cancelar tu seguro sin recargos, cuando quieras, llamando al (02) 2999 999.',
                  track: 'BM_Segu_Frau_01Onbor_Btn_Clk_Accd2',
                },
                {
                  isActive: true,
                  key: 'question_1',
                  order: 0,
                  track: 'BM_Segu_Frau_01Onbor_Btn_Clk_Accd1',
                  title: '¿Cómo usar el seguro?',
                  answer:
                    'Reporta tu caso lo más pronto posible llamando al (02) 299 9999, ellos te guiarán en el proceso hasta la recuperación de tu dinero.',
                },
              ],
              title: {
                isActive: true,
                key: 'title',
                order: 0,
                aria: 'Preguntas frecuentes, sección con tres opciones desplegables.',
                value: 'Preguntas frecuentes',
              },
            },
            toolbar: {
              isActive: true,
              key: 'toolbar',
              order: 0,
              title: {
                isActive: true,
                key: 'title',
                order: 0,
                value: 'Seguro por robos y fraudes',
                aria: 'Conoce el seguro por robos y fraudes',
              },
            },
            coverages: [
              {
                isActive: true,
                key: 'COBE004',
                order: 3,
                title: 'Recupera hasta $600 al año',
                description:
                  'Para reponer tus documentos, bolso, billetera, gafas o maquillaje robados.',
                aria: 'Recupera hasta 600 dólares al año, por robo de tu billetera o bolso: Para reponer tus documentos, bolso, billetera, gafas o maquillaje robados.',
                icon: 'account_balance_wallet',
                subTitle: 'por robo de tu billetera o bolso:',
              },
              {
                isActive: true,
                key: 'COBE002',
                order: 1,
                title: 'Recupera hasta $1.400 al año',
                description:
                  'Dinero en efectivo robado hasta dos horas después de su retiro.',
                icon: 'local_atm',
                aria: 'Recupera hasta 1400 dólares al año, por robos en cajeros o ventanillas:: Dinero en efectivo robado hasta dos horas después de su retiro.',
                subTitle: 'por robos en cajeros o ventanillas:',
              },
              {
                isActive: true,
                key: 'COBE001',
                order: 0,
                title: 'Recupera hasta $10.000 al año',
                description:
                  'Transferencias, retiros y consumos  no autorizados, por asalto o secuestro.',
                icon: 'devices',
                subTitle: 'por cargos fraudulentos:',
                aria: 'Recupera hasta 10000 dólares, por cargos fraudulentos: Transferencias, retiros y consumos  no autorizados, por asalto o secuestro.',
              },
              {
                isActive: true,
                key: 'COBE003',
                order: 2,
                icon: 'shopping_bag',
                description:
                  'Artículos que fueron robados o resultaron dañados accidentalmente.',
                title: 'Recupera hasta $1.000 al año',
                subTitle: 'por compras de tus tarjetas:',
                aria: 'Recupera hasta 1000 dólares al año, por compras de tus tarjetas: Artículos que fueron robados o resultaron dañados accidentalmente.',
              },
              {
                isActive: true,
                key: 'COBE005',
                order: 4,
                description:
                  'Gastos reportados por lesiones hasta  doce horas después del robo.',
                icon: 'medical_services',
                subTitle: 'por primeros auxilios:',
                title: 'Recupera hasta $200 al año',
                aria: 'Recupera hasta 200 dólares al año, por primeros auxilios: Gastos reportados por lesiones hasta doce horas después del robo.',
              },
            ],
            actions: {
              isActive: true,
              key: 'actions',
              order: 12,
              cta: {
                isActive: true,
                key: 'cta',
                order: 5,
                aria: 'Continuar',
                value: 'Continuar',
              },
            },
            legal: {
              isActive: true,
              key: 'legal',
              order: 7,
              action: 'Tratamiento de Mis Datos Personales.',
              description: 'He leído y comprendo la autorización para el ',
            },
          },
        },
        params: {},
      },
      hasOffer: true,
    },
    TU_BAN_PRO: {
      code: 'TU_BAN_PRO',
      name: 'Seguro tu banca protegida',
      sale: null,
      coverages: {
        COBE176: {
          id: 'd0f3b3e5-b615-49fe-3fdf-08db5550afc5',
          name: 'Cargos fraudulentos',
          isActive: true,
          limitValueMin: 0,
          limitValueMax: 0,
          limitEventMin: 0,
          limitEventMax: 0,
        },
        COBE177: {
          id: 'b7ac5bd1-d532-47e5-3fe0-08db5550afc5',
          name: 'Robos en cajeros o ventanillas',
          isActive: true,
          limitValueMin: 0,
          limitValueMax: 0,
          limitEventMin: 0,
          limitEventMax: 0,
        },
        COBE178: {
          id: '68f852eb-b07b-4f04-3fe1-08db5550afc5',
          name: 'Compras de tus tarjetas',
          isActive: true,
          limitValueMin: 0,
          limitValueMax: 0,
          limitEventMin: 0,
          limitEventMax: 0,
        },
        COBE179: {
          id: '7ed15d00-ecac-4e6e-3fe2-08db5550afc5',
          name: 'Robo de tu billetera o bolso',
          isActive: true,
          limitValueMin: 0,
          limitValueMax: 0,
          limitEventMin: 0,
          limitEventMax: 0,
        },
        COBE180: {
          id: '8850cb84-1870-491f-3fe3-08db5550afc5',
          name: 'Primeros auxilios por robo',
          isActive: true,
          limitValueMin: 0,
          limitValueMax: 0,
          limitEventMin: 0,
          limitEventMax: 0,
        },
      },
      benefits: {},
      assistances: {},
      exclusions: {},
      insuranceName: 'AIG Metropolitana',
      plans: {
        TU_BAN_PRO_2: {
          name: 'Cobertura Total',
          coverages: {
            COBE180: {
              name: 'Primeros auxilios por robo',
              isActive: true,
              limitValueMin: 0,
              limitValueMax: 0,
              limitEventMin: 0,
              limitEventMax: 0,
              coverageLimit: {
                minAmount: '0.00',
                maxAmount: '200.00',
                minEvents: 0,
                maxEvents: 2,
              },
            },
            COBE179: {
              name: 'Robo de tu billetera o bolso',
              isActive: true,
              limitValueMin: 0,
              limitValueMax: 0,
              limitEventMin: 0,
              limitEventMax: 0,
              coverageLimit: {
                minAmount: '0.00',
                maxAmount: '600.00',
                minEvents: 0,
                maxEvents: 2,
              },
            },
            COBE178: {
              name: 'Compras de tus tarjetas',
              isActive: true,
              limitValueMin: 0,
              limitValueMax: 0,
              limitEventMin: 0,
              limitEventMax: 0,
              coverageLimit: {
                minAmount: '0.00',
                maxAmount: '1000.00',
                minEvents: 0,
                maxEvents: 2,
              },
            },
            COBE177: {
              name: 'Robos en cajeros o ventanillas',
              isActive: true,
              limitValueMin: 0,
              limitValueMax: 0,
              limitEventMin: 0,
              limitEventMax: 0,
              coverageLimit: {
                minAmount: '0.00',
                maxAmount: '1400.00',
                minEvents: 0,
                maxEvents: 2,
              },
            },
            COBE176: {
              name: 'Cargos fraudulentos',
              isActive: true,
              limitValueMin: 0,
              limitValueMax: 0,
              limitEventMin: 0,
              limitEventMax: 0,
              coverageLimit: {
                minAmount: '0.00',
                maxAmount: '10000.00',
                minEvents: 0,
                maxEvents: 2,
              },
            },
          },
          periodicityOptions: {
            ANNUAL: {
              description: 'Pago anual',
              factor: 12,
              name: 'Anual',
              order: 2,
              price: '37.68',
              totalPrice: '45.07',
              taxes: '5.88',
            },
            MONTHLY: {
              description: 'Pago mensual',
              factor: 1,
              name: 'Mensual',
              order: 1,
              price: '3.42',
              totalPrice: '4.09',
              taxes: '0.53',
            },
          },
          paymentMethodOptions: {
            BANK_ACCOUNT: {
              description: 'Cuenta bancaria',
              name: 'Cuenta',
              order: 1,
            },
            CREDIT_CARD: {
              description: 'Tarjeta de crédito',
              name: 'Tarjeta de crédito',
              order: 2,
            },
          },
        },
      },
      portal: {
        code: 'POR_BP_BANCAMOVIL_TU_BAN_PRO',
        isActive: true,
        content: {
          productInfo: {
            toolbar: {
              isActive: true,
              key: 'toolbar',
              order: 1,
              title: {
                isActive: true,
                key: 'title',
                order: 0,
                aria: 'Seguro por robos y fraudes',
                value: 'Seguro por robos y fraudes',
              },
            },
            select: {
              isActive: true,
              key: 'select',
              order: 4,
              multipleAccount: 'Cuenta a debitar el seguro',
              singleAccount: 'Cuenta a debitar el seguro',
            },
            actions: {
              isActive: true,
              key: 'actions',
              order: 10,
              cta: {
                isActive: true,
                key: 'cta',
                order: 6,
                aria: {
                  isActive: true,
                  key: 'aria',
                  order: 1,
                  enabled: 'Aceptar',
                  disabled:
                    'Para continuar marca la casilla de autorización anterior. Aceptar botón desactivado',
                },
                value: 'Aceptar',
              },
            },
            alert: {
              isActive: true,
              key: 'alert',
              order: 3,
              aria: 'Puedes cancelar en cualquier momento.',
              description: 'Puedes cancelar en cualquier momento.',
            },
            disclaimer: {
              isActive: true,
              key: 'disclaimer',
              order: 5,
              action: 'Cobertura Total.',
              description:
                'Autorizo el débito recurrente y a compartir el medio de pago con el prestador del servicio y Novaecuador S.A. para contratar el seguro por robos y fraudes ',
            },
            description: {
              isActive: true,
              key: 'description',
              order: 2,
              value: 'Un producto de AIG Metropolitana',
              aria: 'Un producto de AIG Metropolitana',
            },
            title: 'Plan Cobertura Total',
            information: 'El valor a pagar incluye impuestos',
          },
          acceptance: {
            actions: {
              isActive: true,
              key: 'actions',
              order: 8,
              btnCancel: {
                isActive: true,
                key: 'btnCancel',
                order: 0,
                value: 'Cancelar',
                aria: 'Cancelar y vuelve al inicio',
              },
              cta: {
                isActive: true,
                key: 'cta',
                order: 7,
                value: 'Confirmar',
                aria: 'Confirmar contratación',
              },
            },
            descriptions: {
              isActive: true,
              key: 'descriptions',
              order: 1,
              companyName: 'Novaecuador S.A.',
              policy: 'Póliza maestra nro.: 50157',
              toCompany: 'A la empresa:',
              from: 'De la cuenta: {0}',
              productName: 'Seguro por robos y fraudes. Cobertura Total',
              forProduct: 'Por el producto:',
              aria: 'Vas a pagar {1}. De la cuenta: {0}. A la empresa: Novaecuador S.A. Por el producto: Seguro por robos y fraudes. Cobertura total. Póliza maestra número: 5 0 1 5 7',
              toPay: 'Vas a pagar {1}: {0} inc. impuestos',
            },
            title: 'Confirma los datos para la contratación',
            toolbar: {
              isActive: true,
              key: 'toolbar',
              order: 3,
              title: {
                isActive: true,
                key: 'title',
                order: 0,
                aria: 'Seguro por robos y fraudes',
                value: 'Seguro por robos y fraudes',
              },
            },
          },
          productDetail: {
            actions: {
              isActive: true,
              key: 'actions',
              order: 12,
              cta: {
                isActive: true,
                key: 'cta',
                order: 5,
                aria: 'Continuar',
                value: 'Continuar',
              },
            },
            alert: {
              isActive: true,
              key: 'alert',
              order: 3,
              action: {
                isActive: true,
                key: 'action',
                order: 1,
                value: 'Conoce más del seguro por robos y fraudes',
                aria: 'Descargar guía de uso del seguro por robos y fraudes',
              },
              description:
                'Puedes ser cubierto hasta 2 veces al año o hasta cubrir el valor máximo anual por caso.',
            },
            description: {
              isActive: true,
              key: 'description',
              order: 1,
              value: 'Mantén tus cuentas y tarjetas de crédito protegidas ¡siempre!',
              aria: 'Con un pago mensual de 4 dólares con 9 centavos recupera tu dinero perdido en los siguientes casos, lista con 6 beneficios:',
            },
            toolbar: {
              isActive: true,
              key: 'toolbar',
              order: 0,
              title: {
                isActive: true,
                key: 'title',
                order: 0,
                aria: 'Conoce el seguro por robos y fraudes',
                value: 'Seguro por robos y fraudes',
              },
            },
            coverages: [
              {
                isActive: true,
                key: 'COBE005',
                order: 4,
                aria: 'Recupera hasta 200 dólares al año, por primeros auxilios: Gastos reportados por lesiones hasta doce horas después del robo.',
                title: 'Recupera hasta $200 al año',
                icon: 'medical_services',
                subTitle: 'por primeros auxilios:',
                description:
                  'Gastos reportados por lesiones hasta  doce horas después del robo.',
              },
              {
                isActive: true,
                key: 'COBE003',
                order: 2,
                description:
                  'Artículos que fueron robados o resultaron dañados accidentalmente.',
                icon: 'shopping_bag',
                subTitle: 'por compras de tus tarjetas:',
                title: 'Recupera hasta $1.000 al año',
                aria: 'Recupera hasta 1000 dólares al año, por compras de tus tarjetas: Artículos que fueron robados o resultaron dañados accidentalmente.',
              },
              {
                isActive: true,
                key: 'COBE002',
                order: 1,
                aria: 'Recupera hasta 1400 dólares al año, por robos en cajeros o ventanillas:: Dinero en efectivo robado hasta dos horas después de su retiro.',
                title: 'Recupera hasta $1.400 al año',
                description:
                  'Dinero en efectivo robado hasta dos horas después de su retiro.',
                subTitle: 'por robos en cajeros o ventanillas:',
                icon: 'local_atm',
              },
              {
                isActive: true,
                key: 'COBE001',
                order: 0,
                description:
                  'Transferencias, retiros y consumos  no autorizados, por asalto o secuestro.',
                icon: 'devices',
                subTitle: 'por cargos fraudulentos:',
                aria: 'Recupera hasta 10000 dólares, por cargos fraudulentos: Transferencias, retiros y consumos  no autorizados, por asalto o secuestro.',
                title: 'Recupera hasta $10.000 al año',
              },
              {
                isActive: true,
                key: 'COBE004',
                order: 3,
                icon: 'account_balance_wallet',
                title: 'Recupera hasta $600 al año',
                aria: 'Recupera hasta 600 dólares al año, por robo de tu billetera o bolso: Para reponer tus documentos, bolso, billetera, gafas o maquillaje robados.',
                description:
                  'Para reponer tus documentos, bolso, billetera, gafas o maquillaje robados.',
                subTitle: 'por robo de tu billetera o bolso:',
              },
            ],
            title: {
              isActive: true,
              key: 'title',
              order: 1,
              aria: 'Un seguro que protege tu dinero por 4 dólares con 9 centavos al mes',
              value: 'Un seguro que protege tu dinero por $4,09 al mes',
            },
            faq: {
              isActive: true,
              key: 'faq',
              order: 4,
              title: {
                isActive: true,
                key: 'title',
                order: 0,
                value: 'Preguntas frecuentes',
                aria: 'Preguntas frecuentes, sección con tres opciones desplegables.',
              },
              questions: [
                {
                  isActive: true,
                  key: 'question_1',
                  order: 0,
                  track: 'BM_Segu_Frau_01Onbor_Btn_Clk_Accd1',
                  title: '¿Cómo usar el seguro?',
                  answer:
                    'Reporta tu caso lo más pronto posible llamando al (02) 299 9999, ellos te guiarán en el proceso hasta la recuperación de tu dinero.',
                },
                {
                  isActive: true,
                  key: 'question_3',
                  order: 2,
                  track: 'BM_Segu_Frau_01Onbor_Btn_Clk_Accd3',
                  title: '¿Quién respalda este producto?',
                  answer:
                    'Es un producto de AIG Metropolitana de seguros con el asesoramiento y gestión de Novaecuador S.A.',
                },
                {
                  isActive: true,
                  key: 'question_2',
                  order: 1,
                  answer:
                    'Puedes cancelar tu seguro sin recargos, cuando quieras, llamando al (02) 2999 999.',
                  title: '¿Cómo cancelo?',
                  track: 'BM_Segu_Frau_01Onbor_Btn_Clk_Accd2',
                },
              ],
            },
            legal: {
              isActive: true,
              key: 'legal',
              order: 7,
              description: 'He leído y comprendo la autorización para el ',
              action: 'Tratamiento de Mis Datos Personales.',
            },
          },
          sale: {
            description: {
              isActive: true,
              key: 'description',
              order: 2,
              value: 'Plan Cobertura Total | {0}',
              aria: 'Plan Cobertura Total, por {0}',
            },
            insuranceCarrier: {
              isActive: true,
              key: 'insuranceCarrier',
              order: 3,
              label: 'Un producto de:',
              aria: 'Un producto de: AIG Metropolitana',
              value: 'AIG Metropolitana',
            },
            coverages: {
              isActive: true,
              key: 'coverages',
              order: 4,
              items: [
                {
                  isActive: true,
                  key: 'COBE004',
                  order: 3,
                  value: '$ 600',
                  label: 'Robos de billetera o bolso',
                  aria: 'Robos de billetera o bolso,  600 dólares',
                },
                {
                  isActive: true,
                  key: 'COBE005',
                  order: 4,
                  value: '$ 200',
                  aria: 'Primeros auxilios por robo en cajero, 200 dólares',
                  label: 'Primeros auxilios por robo en cajero',
                },
                {
                  isActive: true,
                  key: 'COBE001',
                  order: 0,
                  aria: 'Cargos fraudulentos, 10000 dólares.',
                  label: 'Cargos fraudulentos',
                  value: '$ 10.000',
                },
                {
                  isActive: true,
                  key: 'COBE003',
                  order: 2,
                  value: '$ 1.000',
                  aria: 'Compras con tus tarjetas,  1000 dólares',
                  label: 'Compras con tus tarjetas',
                },
                {
                  isActive: true,
                  key: 'COBE002',
                  order: 1,
                  aria: 'Robos en cajeros o ventanillas, 1400 dólares',
                  label: 'Robos en cajeros o ventanillas',
                  value: '$ 1.400',
                },
              ],
              headers: {
                isActive: true,
                key: 'headers',
                order: 1,
                value: 'Máximo anual',
                label: 'Casos',
              },
              description: {
                isActive: true,
                key: 'description',
                order: 0,
                aria: 'Recuerda que puedes usar 2 veces cada caso hasta cubrir el máximo anual',
                value:
                  'Recuerda que puedes usar 2 veces cada caso hasta cubrir el máximo anual',
              },
            },
            toolbar: 'Default value',
            contract: {
              isActive: true,
              key: 'contract',
              order: 1,
              aria: 'Número de contrato:  {0}',
              value: 'Nro. contrato:  {0}',
            },
            title: 'Seguro por robos y fraudes',
            range: {
              isActive: true,
              key: 'range',
              order: 3,
              aria: 'Tu fecha de contratación fue: {0}, los débitos se realizan todos los {1}',
              items: [
                {
                  isActive: true,
                  key: 'range_2',
                  order: 1,
                  value: '{1}',
                  label: 'Fecha débito',
                },
                {
                  isActive: true,
                  key: 'range_1',
                  order: 0,
                  label: 'Fecha de contratación',
                  value: '{0}',
                },
              ],
            },
            faq: {
              isActive: true,
              key: 'faq',
              order: 5,
              title: {
                isActive: true,
                key: 'title',
                order: 0,
                value: 'Preguntas frecuentes',
                aria: 'Preguntas frecuentes, sección con tres opciones desplegables.',
              },
              questions: [
                {
                  isActive: true,
                  key: 'question_2',
                  order: 1,
                  title: '¿Cómo cancelo?',
                  answer:
                    'Puedes cancelar tu seguro sin recargos, cuando quieras, llamando al (02) 2999 999.',
                  track: 'BM_Segu_Frau_05Posventa_Btn_Clk_Accd2',
                },
                {
                  isActive: true,
                  key: 'question_3',
                  order: 2,
                  track: 'BM_Segu_Frau_05Posventa_Btn_Clk_Accd3',
                  answer:
                    'Es un producto de AIG Metropolitana de seguros con el asesoramiento y gestión de Novaecuador S.A.',
                  title: '¿Quién respalda este producto?',
                },
                {
                  isActive: true,
                  key: 'question_1',
                  order: 0,
                  title: '¿Cómo usar el seguro?',
                  answer:
                    'Reporta tu caso lo más pronto posible llamando al (02) 299 9999, ellos te guiarán en el proceso hasta la recuperación de tu dinero.',
                  track: 'BM_Segu_Frau_05Posventa_Btn_Clk_Accd1',
                },
              ],
            },
            actions: {
              cta: {
                isActive: true,
                key: 'cta',
                order: 2,
                value: 'Cómo usar tu seguro',
                aria: 'Cómo usar tu seguro',
              },
              userGuide: {
                isActive: true,
                key: 'userGuide',
                order: 0,
                aria: 'Descargar certificado',
                value: 'guia-de-uso-frauds',
              },
              call: {
                isActive: true,
                key: 'call',
                order: 0,
                value: 'tel:029999999',
                aria: 'Llámanos 24 horas 7 días a la semana',
              },
              whatsapp: {
                isActive: true,
                key: 'whatsapp',
                order: 1,
                aria: 'Escríbenos al WhatsApp',
                value:
                  'https://api.whatsapp.com/send?phone=593995546002&text=Hola,%20vengo%20de%20mi%20Banca%20M%C3%B3vil%20de%20Banco%20Pichincha%20y%20necesito%20informaci%C3%B3n%20sobre%20mi%20seguro%20por%20robos%20y%20fraudes.',
              },
            },
          },
          selectAccount: {
            title: {
              isActive: true,
              key: 'title',
              order: 0,
              aria: 'Selecciona entre tus cuentas',
              value: 'Mis cuentas',
            },
            toolbar: {
              isActive: true,
              key: 'toolbar',
              order: 2,
              title: {
                isActive: true,
                key: 'title',
                order: 0,
                value: 'Elige tu cuenta',
                aria: 'Elige tu cuenta',
              },
            },
          },
          multiOffer: {
            offer: {
              isActive: true,
              key: 'offer',
              order: 7,
              description: '$2,77 /mes',
              title: 'Seguro por robo y fraude',
            },
            previous: {
              isActive: true,
              key: 'previous',
              order: 8,
              description: 'Protección por cargos fraudulentos',
              title: 'Seguro por robos y fraudes',
            },
          },
          success: {
            details: [
              {
                isActive: true,
                key: 'item_3',
                order: 2,
                subItems: [
                  {
                    isActive: true,
                    key: 'subItem_1',
                    order: 0,
                    label: 'Fecha de vencimiento',
                    value: 'Indefinido',
                  },
                  {
                    isActive: true,
                    key: 'subItem_2',
                    order: 1,
                    value: '{2}',
                    label: 'Fecha de contratación',
                  },
                ],
                aria: 'Fecha de vencimiento Indefinido, fecha de contratación {3}',
              },
              {
                isActive: true,
                key: 'item_2',
                order: 1,
                subItems: [
                  {
                    isActive: true,
                    key: 'subItem_2',
                    order: 1,
                    label: 'Fecha para débitos',
                    value: '{1} de cada mes',
                  },
                  {
                    isActive: true,
                    key: 'subItem_1',
                    order: 0,
                    label: 'Cuenta de débito',
                    value: '{0}',
                  },
                ],
                aria: 'Cuenta de débito termina en {4}, fecha para débitos {1}',
              },
              {
                isActive: true,
                key: 'item_1',
                order: 0,
                aria: 'Seguro por robos y fraudes, cobertura total. Precio incluido impuesto',
                subItems: [
                  {
                    isActive: true,
                    key: 'subitem_2',
                    order: 1,
                    value: 'Cobertura Total',
                    label: 'Seguro por robos y fraudes',
                  },
                  {
                    isActive: true,
                    key: 'subItem_1',
                    order: 0,
                    value: '{5}',
                    label: 'Precio incluido impuestos',
                  },
                ],
              },
            ],
            moreInformation: {
              isActive: true,
              key: 'moreInformation',
              order: 4,
              description: {
                isActive: true,
                key: 'description',
                order: 0,
                value: 'Para requerimientos o más información',
                aria: 'Si tienes requerimientos o más información, comunícate a Banca telefónica.',
              },
              action: {
                isActive: true,
                key: 'action',
                order: 0,
                aria: 'Llamar (02) 2999 999',
                label: 'Llámanos al (02)2999 999',
                link: 'tel:022999999',
              },
            },
            toolbar: {
              isActive: true,
              key: 'toolbar',
              order: 4,
              title: {
                isActive: true,
                key: 'title',
                order: 0,
                aria: 'Banco Pichincha',
                value: 'Banco Pichincha',
              },
            },
            actions: {
              isActive: true,
              key: 'actions',
              order: 9,
              btnDownload: {
                isActive: true,
                key: 'btnDownload',
                order: 1,
                aria: 'Descargar guía de uso del Seguro',
                value: 'Cómo usar tu seguro',
              },
              cta: {
                isActive: true,
                key: 'cta',
                order: 0,
                aria: 'Finalizar',
                value: 'Finalizar',
              },
            },
            description: 'Póliza maestra nro.: 50157',
            title: {
              isActive: true,
              key: 'title',
              order: 0,
              value: '¡Contratación exitosa!',
              aria: 'Tu contratacion fue exitosa',
            },
            alert: {
              isActive: true,
              key: 'alert',
              order: 2,
              value: 'Enviamos a tu correo el certificado',
              aria: 'Enviamos a tu correo el certificado del seguro',
            },
          },
          home: {
            sectionHero: {
              isActive: true,
              key: 'sectionHero',
              order: 0,
              title: {
                isActive: true,
                key: 'title',
                order: 0,
                value: 'Protección adicional desde el primer dia, por $4,09 al mes',
                aria: 'Protección adicional desde el primer dia, por $4,09 al mes',
              },
              description: {
                isActive: true,
                key: 'description',
                order: 1,
                value:
                  'Añade una capa extra de seguridad a tus cuentas y tarjetas de Banco Pichincha.',
                aria: 'Añade una capa extra de seguridad a tus cuentas y tarjetas de Banco Pichincha.',
              },
            },
            sectionFaq: {
              isActive: true,
              key: 'sectionFaq',
              order: 1,
              description: {
                isActive: true,
                key: 'description',
                order: 1,
                value: 'Esto es lo que cubre tu seguro:',
                aria: 'Esto es lo que cubre tu seguro:',
              },
              questions: [
                {
                  isActive: true,
                  key: 'question-1',
                  order: 0,
                  question: {
                    isActive: true,
                    key: 'question',
                    order: 0,
                    value: 'Hasta $10.000 al año, por cargos que no reconoces',
                    aria: 'Hasta $10.000 al año, por cargos que no reconoces',
                  },
                  answer: {
                    isActive: true,
                    key: 'answer',
                    order: 1,
                    value:
                      ' <ul className="ml-24 list-disc">\r\n    <li className="mb-8"> \r\n        Si usan tu tarjeta o cuenta para realizar compras, retiros o transferencias no autorizadas por ti, estás cubierto, <strong>incluso si las haces tú mismo bajo amenaza.</strong>\r\n  </li> \r\n    <li className="mb-8">\r\n        Descarga esta guía para entender cómo funciona el uso de tus 2 casos por año.\r\n    </li>\r\n </ul>',
                    aria: 'Default value',
                  },
                  track: 'trak 001',
                  icon: 'devices',
                },
                {
                  isActive: true,
                  key: 'question-2',
                  order: 1,
                  question: {
                    isActive: true,
                    key: 'question',
                    order: 0,
                    value: 'Hasta $1.400 al año, por robo después de retirar dinero',
                    aria: 'Hasta $1.400 al año, por robo después de retirar dinero',
                  },
                  answer: {
                    isActive: true,
                    key: 'answer',
                    order: 1,
                    value:
                      '<ul className="ml-24 list-disc">\r\n    <li className="mb-8"> \r\n        Si retiras dinero del cajero o por ventanilla, estás protegido durante las siguientes dos horas. Si te roban ese dinero en este tiempo, <strong>te lo devolvemos.</strong>\r\n     </li> \r\n    <li className="mb-8">\r\n        Si sufres alguna lesión durante el asalto, te cubrimos hasta $200 en gastos de primeros auxilios. \r\n    </li>\r\n </ul>',
                    aria: 'Default value',
                  },
                  track: 'local_atm',
                  icon: 'local_atm',
                },
                {
                  isActive: true,
                  key: 'question-3',
                  order: 2,
                  question: {
                    isActive: true,
                    key: 'question',
                    order: 0,
                    value: 'Hasta $1.000 al año por daños o robo a productos',
                    aria: 'Hasta $1.000 al año por daños o robo a productos',
                  },
                  answer: {
                    isActive: true,
                    key: 'answer',
                    order: 1,
                    value:
                      '<ul className="ml-24 list-disc">\r\n    <li className="mb-8"> \r\n        Si los productos que compres con <strong>tu tarjeta de Banco Pichincha</strong> sufren daños accidentales o robos, <strong>estás protegido</strong> hasta $1.000.\r\n  </li> \r\n    <li className="mb-8">\r\n        <strong>Por ejemplo:</strong> Si compras un celular y este sufre un daño accidental que lo deja inservible o es robado, te devolvemos su valor. \r\n    </li>\r\n </ul>',
                    aria: 'Default value',
                  },
                  track: 'Default value',
                  icon: 'shopping_bag',
                },
                {
                  isActive: true,
                  key: 'question-4',
                  order: 3,
                  question: {
                    isActive: true,
                    key: 'question',
                    order: 0,
                    value: 'Hasta $600 al año por robo de tu billetera o bolso',
                    aria: 'Hasta $600 al año por robo de tu billetera o bolso',
                  },
                  answer: {
                    isActive: true,
                    key: 'answer',
                    order: 1,
                    value:
                      '<ul className="ml-24 list-disc">\r\n    <li className="mb-8"> \r\n        Si te roban el bolso o billetera, te cubrimos hasta $600 para ayudarte a reponer lo que llevabas y cubrir los gastos de actualización de documentos. \r\n     </li> \r\n    <li className="mb-8">\r\n        Los artículos cubiertos son: documentos de identidad, tarjetas, gafas y maquillaje.\r\n    </li>\r\n </ul>\r\n',
                    aria: 'Default value',
                  },
                  track: 'Default value',
                  icon: 'account_balance_wallet',
                },
              ],
              alert: {
                isActive: true,
                key: 'alert',
                order: 3,
                value:
                  'Puedes usar cada cobertura hasta 2 veces al año o hasta alcanzar el monto máximo, y también usarlas al mismo tiempo.',
                aria: 'Puedes usar cada cobertura hasta 2 veces al año o hasta alcanzar el monto máximo, y también usarlas al mismo tiempo.',
              },
            },
            sectionCoverages: {
              isActive: true,
              key: 'sectionCoverages',
              order: 2,
              actionShowCoverages: {
                isActive: true,
                key: 'actionShowCoverages',
                order: 0,
                value: 'Saber más del seguro',
                aria: 'Saber más del seguro',
              },
              actionNext: {
                isActive: true,
                key: 'actionNext',
                order: 1,
                value: 'Elige tu método de pago',
                aria: 'Elige tu método de pago',
              },
              title: {
                isActive: true,
                key: 'title',
                order: 3,
                value: 'Transparencia total',
                aria: 'Transparencia total',
              },
              coverages: {
                isActive: true,
                key: 'coverages',
                order: 5,
                items: [
                  {
                    isActive: true,
                    key: 'COB_1',
                    order: 0,
                    description: {
                      isActive: true,
                      key: 'description',
                      order: 0,
                      value: 'Desde el primer día de contratación.',
                      aria: 'Desde el primer día de contratación.',
                    },
                    icon: {
                      isActive: true,
                      key: 'icon',
                      order: 1,
                      value: 'check',
                      color: 'darkCyan',
                    },
                  },
                  {
                    isActive: true,
                    key: 'COB_2',
                    order: 1,
                    description: {
                      isActive: true,
                      key: 'description',
                      order: 0,
                      value:
                        'Todas tus cuentas de ahorro y corriente en Banco Pichincha, incluidas sus tarjetas de débito.',
                      aria: 'Todas tus cuentas de ahorro y corriente en Banco Pichincha, incluidas sus tarjetas de débito.',
                    },
                    icon: {
                      isActive: true,
                      key: 'icon',
                      order: 1,
                      value: 'check',
                      color: 'darkCyan',
                    },
                  },
                  {
                    isActive: true,
                    key: 'COB_4',
                    order: 3,
                    description: {
                      isActive: true,
                      key: 'description',
                      order: 0,
                      value:
                        'Documentos personales: cédula, pasaporte, licencia de conducir.',
                      aria: 'Documentos personales: cédula, pasaporte, licencia de conducir.',
                    },
                    icon: {
                      isActive: true,
                      key: 'icon',
                      order: 1,
                      value: 'check',
                      color: 'darkCyan',
                    },
                  },
                  {
                    isActive: true,
                    key: 'COB_5',
                    order: 4,
                    description: {
                      isActive: true,
                      key: 'description',
                      order: 0,
                      value:
                        'Dinero retirado en cajeros automáticos o ventanillas de Banco Pichincha.',
                      aria: 'Dinero retirado en cajeros automáticos o ventanillas de Banco Pichincha.',
                    },
                    icon: {
                      isActive: true,
                      key: 'icon',
                      order: 1,
                      value: 'check',
                      color: 'darkCyan',
                    },
                  },
                  {
                    isActive: true,
                    key: 'COB_3',
                    order: 2,
                    description: {
                      isActive: true,
                      key: 'description',
                      order: 0,
                      value: 'Todas tus tarjetas de crédito Banco Pichincha.',
                      aria: 'Todas tus tarjetas de crédito Banco Pichincha.',
                    },
                    icon: {
                      isActive: true,
                      key: 'icon',
                      order: 1,
                      value: 'check',
                      color: 'darkCyan',
                    },
                  },
                  {
                    isActive: true,
                    key: 'COB_6',
                    order: 5,
                    description: {
                      isActive: true,
                      key: 'description',
                      order: 0,
                      value:
                        'Hasta 2 eventos al año o hasta el monto máximo anual de cobertura.',
                      aria: 'Hasta 2 eventos al año o hasta el monto máximo anual de cobertura.',
                    },
                    icon: {
                      isActive: true,
                      key: 'icon',
                      order: 1,
                      value: 'check',
                      color: 'darkCyan',
                    },
                  },
                  {
                    isActive: true,
                    key: 'COB_7',
                    order: 6,
                    description: {
                      isActive: true,
                      key: 'description',
                      order: 0,
                      value:
                        'Para cualquier consulta o para hacer uso de tu seguro, comunícate al 096 403 9999.',
                      aria: 'Para cualquier consulta o para hacer uso de tu seguro, comunícate al 096 403 9999.',
                    },
                    icon: {
                      isActive: true,
                      key: 'icon',
                      order: 1,
                      value: 'check',
                      color: 'darkCyan',
                    },
                  },
                ],
                title: {
                  isActive: true,
                  key: 'title',
                  order: 0,
                  value: 'Si cubrimos...',
                  aria: 'Si cubrimos...',
                },
              },
              description: {
                isActive: true,
                key: 'description',
                order: 4,
                value:
                  'Conoce qué incluye tu seguro y qué situaciones no están cubiertas.',
                aria: 'Conoce qué incluye tu seguro y qué situaciones no están cubiertas.',
              },
              exclusions: {
                isActive: true,
                key: 'exclusions',
                order: 6,
                items: [
                  {
                    isActive: true,
                    key: 'EXC_1',
                    order: 0,
                    description: {
                      isActive: true,
                      key: 'description',
                      order: 0,
                      value: 'Tarjetas y cuentas de otros bancos.',
                      aria: 'Tarjetas y cuentas de otros bancos.',
                    },
                    icon: {
                      isActive: true,
                      key: 'icon',
                      order: 1,
                      value: 'close',
                      color: 'error',
                    },
                  },
                  {
                    isActive: true,
                    key: 'EXC_2',
                    order: 1,
                    description: {
                      isActive: true,
                      key: 'description',
                      order: 0,
                      value: 'Casos ocurridos antes de contratar el seguro.',
                      aria: 'Casos ocurridos antes de contratar el seguro.',
                    },
                    icon: {
                      isActive: true,
                      key: 'icon',
                      order: 1,
                      value: 'close',
                      color: 'error',
                    },
                  },
                  {
                    isActive: true,
                    key: 'EXC_4',
                    order: 3,
                    description: {
                      isActive: true,
                      key: 'description',
                      order: 0,
                      value:
                        'Reportes realizados después de 72 horas o con documentación incompleta tras 30 días.',
                      aria: 'Reportes realizados después de 72 horas o con documentación incompleta tras 30 días.',
                    },
                    icon: {
                      isActive: true,
                      key: 'icon',
                      order: 1,
                      value: 'close',
                      color: 'error',
                    },
                  },
                  {
                    isActive: true,
                    key: 'EXC_5',
                    order: 4,
                    description: {
                      isActive: true,
                      key: 'description',
                      order: 0,
                      value:
                        'Eventos provocados por un familiar o alguien que vive contigo.',
                      aria: 'Eventos provocados por un familiar o alguien que vive contigo.',
                    },
                    icon: {
                      isActive: true,
                      key: 'icon',
                      order: 1,
                      value: 'close',
                      color: 'error',
                    },
                  },
                  {
                    isActive: true,
                    key: 'EXC_3',
                    order: 2,
                    description: {
                      isActive: true,
                      key: 'description',
                      order: 0,
                      value:
                        'Situaciones en las que el pago del seguro no esté al día.',
                      aria: 'Situaciones en las que el pago del seguro no esté al día.',
                    },
                    icon: {
                      isActive: true,
                      key: 'icon',
                      order: 1,
                      value: 'close',
                      color: 'error',
                    },
                  },
                  {
                    isActive: true,
                    key: 'EXC_6',
                    order: 5,
                    description: {
                      isActive: true,
                      key: 'description',
                      order: 0,
                      value:
                        'Más de 2 casos al año o montos que superen el límite anual.',
                      aria: 'Más de 2 casos al año o montos que superen el límite anual.',
                    },
                    icon: {
                      isActive: true,
                      key: 'icon',
                      order: 1,
                      value: 'close',
                      color: 'error',
                    },
                  },
                ],
                title: {
                  isActive: true,
                  key: 'title',
                  order: 0,
                  value: 'No cubrimos...',
                  aria: 'No cubrimos...',
                },
              },
              actionDownloadCertificate: {
                isActive: true,
                key: 'actionDownloadCertificate',
                order: 2,
                value: 'Previsualizar certificado',
                aria: 'Previsualizar certificado',
              },
            },
          },
          flow: {
            steps: [
              {
                isActive: true,
                key: 'step1',
                order: 0,
                route: 'PRODUCT_DETAIL',
              },
              {
                isActive: true,
                key: 'step2',
                order: 1,
                route: 'PRODUCT',
              },
              {
                isActive: true,
                key: 'step3',
                order: 2,
                route: 'SELECT_ACCOUNT',
              },
              {
                isActive: true,
                key: 'step4',
                order: 3,
                route: 'ACCEPTANCE',
              },
              {
                isActive: true,
                key: 'step5',
                order: 4,
                route: 'SUCCESS',
              },
            ],
          },
          payment: {
            title: {
              isActive: true,
              key: 'title',
              order: 0,
              value: 'Plan',
              aria: 'Plan',
            },
            toolbar: {
              isActive: true,
              key: 'toolbar',
              order: 3,
              title: {
                isActive: true,
                key: 'title',
                order: 0,
                aria: 'Seguro por robos y fraudes',
                value: 'Seguro por robos y fraudes',
              },
            },
            description: {
              isActive: true,
              key: 'description',
              order: 1,
              value: 'Un producto de AIG Metropolitana',
              aria: 'Un producto de AIG Metropolitana',
            },
            alert: {
              isActive: true,
              key: 'alert',
              order: 3,
              aria: 'Puedes cancelar en cualquier momento.',
              value: 'Puedes cancelar en cualquier momento.',
            },
            disclaimer: {
              isActive: true,
              key: 'disclaimer',
              order: 6,
              value:
                'Autorizo el débito recurrente y a compartir el medio de pago con el prestador del servicio y Novaecuador S.A. para contratar el seguro por robos y fraudes ',
              aria: 'Descargar el documento de cobertura total',
              action: 'Cobertura Total.',
            },
            actionNext: {
              isActive: true,
              key: 'actionNext',
              order: 7,
              cta: {
                isActive: true,
                key: 'cta',
                order: 0,
                aria: {
                  isActive: true,
                  key: 'aria',
                  order: 1,
                  enabled: 'Aceptar',
                  disabled:
                    'Para continuar marca la casilla de autorización anterior. Aceptar botón desactivado',
                },
                value: 'Aceptar',
              },
            },
            paymentMethod: {
              isActive: true,
              key: 'paymentMethod',
              order: 4,
              input: {
                isActive: true,
                key: 'input',
                order: 0,
                value: '¿Cómo quieres pagar tu seguro?',
                aria: '¿Cómo quieres pagar tu seguro?',
              },
            },
            selectAccount: {
              isActive: true,
              key: 'selectAccount',
              order: 5,
              multipleAccount: 'Cuenta a debitar el seguro',
              singleAccount: 'Cuenta a debitar el seguro',
            },
          },
        },
        params: {},
      },
      hasOffer: true,
    },
  },
  accounts: {
    '42e976aea883be9ad3b29487ab3d1a64778bdbfbac9d02f30941d30600b76585': {
      hash: '42e976aea883be9ad3b29487ab3d1a64778bdbfbac9d02f30941d30600b76585',
      mask: '******2008',
      balance: 2000,
      type: 'CHECKING_ACCOUNT',
      alias: 'PRINCIPAL',
      favorite: true,
      value: 'l4YdunhaQNtjnnSr09ftwAdmXFWaEsY1r4I=',
    },
    abf0a7dad05cfe2f3fd9a98ca0fcd93458143b692970cfcabdcf938d06a9f9fc: {
      hash: 'abf0a7dad05cfe2f3fd9a98ca0fcd93458143b692970cfcabdcf938d06a9f9fc',
      mask: '******8092',
      balance: 800,
      type: 'SAVINGS_ACCOUNT',
      alias: null,
      favorite: false,
      value: 'l4UdvnpfSttqlI0BU7R7LE3vX7mOb1fhWNA=',
    },
  },
  lopdp: {
    acceptedTermsConditions: true,
    hasConsent: true,
    url: 'https://www.pichincha.com/portal/Portals/0/Transparencia/autorizacion-para-tratamiento-de-documentos-personales-v02.pdf',
  },
})
