export const enum ErrorCode {
  NOT_ACCOUNTS = '001',
  NOT_TRANSACTIONAL_ACCOUNTS = '002',
  NOT_OFFERABLE_NOT_PREVIOUS = '003',
  FAILED_PROCESS_TRANSACTION = '004',
  INVALID_SOFT_TOKEN = '005',
  TRANSACTION_IN_PROGRESS = '006',

  NOT_CLIENT_INFORMATION = '008',

  FALIED_LOPDP_ACCEPTATION = '010',

  FAILED_OFFERABLE_DATA = '012',
}
