export const enum ErrorCode {
  NOT_ACCOUNTS = '001',
  NOT_TRANSACTIONAL_ACCOUNTS = '002',
  NOT_OFFERABLE_NOT_PREVIOUS = '003',
  FAILED_PROCESS_TRANSACTION = '004',
  INVALID_SOFT_TOKEN = '005',
  TRANSACTION_IN_PROGRESS = '006',

  PREVIOUS_FROM_OTHER_CHANNEL = '099', // Temporary error code
}
