export const enum FlowStatus {
  NORMAL = 'NORMAL',
  WAIT_LOAD = 'WAIT_LOAD',
  RETRY_ACCEPTANCE_INITIAL = 'RETRY_ACCEPTANCE_INITIAL',
  RETRY_ACCEPTANCE_LAST = 'RETRY_ACCEPTANCE_LAST',
  RETRY_ACCEPTANCE_ERROR = 'RETRY_ACCEPTANCE_ERROR',
  END_SUCCESS = 'END_SUCCESS',
  END_ERROR = 'END_ERROR',
}
