export const enum RoutesHubAlias {
  // Hub Page
  HUB_NAME = 'HOME',

  GENERAL_ERROR = 'GENERAL_ERROR',
  NOT_PRODUCT = 'NOT_PRODUCT',
  NOT_ACCOUNT = 'NOT_ACCOUNT',
  PREVIOUS = 'PREVIOUS',
  PREVIOUS_PRODUCT = 'PREVIOUS_PRODUCT',
  ALREADY_PRODUCT = 'ALREADY_PRODUCT',
  RETRY_ACCEPTANCE = 'RETRY_ACCEPTANCE',
  IN_PROGRESS = 'IN_PROGRESS',
}

export const enum RoutesFraudAlias {
  PRODUCT_DETAIL = 'PRODUCT_DETAIL',
  PRODUCT = 'PRODUCT',
  SELECT_ACCOUNT = 'SELECT_ACCOUNT',
  ACCEPTANCE = 'ACCEPTANCE',
  SUCCESS = 'SUCCESS',
}

export const enum RoutesAlias {
  GENERAL_ERROR = 'GENERAL_ERROR',
  NOT_PRODUCT = 'NOT_PRODUCT',
  NOT_ACCOUNT = 'NOT_ACCOUNT',
  PREVIOUS = 'PREVIOUS',
  PREVIOUS_PRODUCT = 'PREVIOUS_PRODUCT',
  ALREADY_PRODUCT = 'ALREADY_PRODUCT',
  RETRY_ACCEPTANCE = 'RETRY_ACCEPTANCE',
  IN_PROGRESS = 'IN_PROGRESS',
}