export const enum RoutesHubAlias {
  // Hub Page
  INSURANCE_PORTAL = 'INSURANCE_PORTAL',
  TERMS_AND_CONDITIONS = 'TERMS_AND_CONDITIONS',

  GENERAL_ERROR = 'GENERAL_ERROR',
  NOT_PRODUCT = 'NOT_PRODUCT',
  NOT_ACCOUNT = 'NOT_ACCOUNT',
  PREVIOUS = 'PREVIOUS',
  PREVIOUS_PRODUCT = 'PREVIOUS_PRODUCT',
  ALREADY_PRODUCT = 'ALREADY_PRODUCT',
  RETRY_ACCEPTANCE = 'RETRY_ACCEPTANCE',
  IN_PROGRESS = 'IN_PROGRESS',
}

export const enum RoutesFraudAlias {
  PRODUCT_DETAIL = 'PRODUCT_DETAIL',
  PRODUCT = 'PRODUCT',
  ACCEPTANCE = 'ACCEPTANCE',
  SUCCESS = 'SUCCESS',
}
