export const enum RoutesHubAlias {
  // Hub Page
  INSURANCE_PORTAL = 'INSURANCE_PORTAL',
  TERMS_AND_CONDITIONS = 'TERMS_AND_CONDITIONS',
  GENERAL_ERROR = 'GENERAL_ERROR',
  NOT_PRODUCT = 'NOT_PRODUCT',
  NOT_ACCOUNT = 'NOT_ACCOUNT',
  PREVIOUS_PRODUCT = 'PREVIOUS_PRODUCT',
  PREVIOUS_PRODUCT_DETAIL = 'PREVIOUS_PRODUCT_DETAIL',
  ALREADY_PRODUCT = 'ALREADY_PRODUCT',
  RETRY_ACCEPTANCE = 'RETRY_ACCEPTANCE',
  IN_PROGRESS = 'IN_PROGRESS',
  NOT_CLIENT_INFORMATION = 'NOT_CLIENT_INFORMATION',
  FAILED_OFFERABLE_DATA = 'FAILED_OFFERABLE_DATA',
}

export const enum RoutesFraudAlias {
  PLAN_SELECTION = 'PLAN_SELECTION',
  PRODUCT_DETAIL = 'PRODUCT_DETAIL',
  PRODUCT = 'PRODUCT',
  ACCEPTANCE = 'ACCEPTANCE',
  SUCCESS = 'SUCCESS',
}
